алӏна<num><mult><part>:алӏовахна
алӏна<num><compord><abs>:алӏнаийāлӏейо
алӏна<num><compord><abs>:алӏнаийāлIейо
алӏна<num><compord><abs>:алӏнаийāл1ейо
алӏна<num><hundred>:алӏначӏитӏ
алӏна<num><hundred>:алӏначӏитI
алӏна<num><hundred>:алӏначӏит1
алӏна<num><hundred>:алӏначIитӏ
алӏна<num><hundred>:алӏначIитI
алӏна<num><hundred>:алӏначIит1
алӏна<num><hundred>:алӏнач1итӏ
алӏна<num><hundred>:алӏнач1итI
алӏна<num><hundred>:алӏнач1ит1
алӏна<num><part>:алӏнана
алӏна<num><ord>:алӏнас
алӏна<num><ten>:алӏнайиг
алӏна<num><mult><part>:алIовахна
алӏна<num><compord><abs>:алIнаийāлӏейо
алӏна<num><compord><abs>:алIнаийāлIейо
алӏна<num><compord><abs>:алIнаийāл1ейо
алӏна<num><hundred>:алIначӏитӏ
алӏна<num><hundred>:алIначӏитI
алӏна<num><hundred>:алIначӏит1
алӏна<num><hundred>:алIначIитӏ
алӏна<num><hundred>:алIначIитI
алӏна<num><hundred>:алIначIит1
алӏна<num><hundred>:алIнач1итӏ
алӏна<num><hundred>:алIнач1итI
алӏна<num><hundred>:алIнач1ит1
алӏна<num><part>:алIнана
алӏна<num><ord>:алIнас
алӏна<num><ten>:алIнайиг
алӏна<num><mult><part>:ал1овахна
алӏна<num><compord><abs>:ал1наийāлӏейо
алӏна<num><compord><abs>:ал1наийāлIейо
алӏна<num><compord><abs>:ал1наийāл1ейо
алӏна<num><hundred>:ал1начӏитӏ
алӏна<num><hundred>:ал1начӏитI
алӏна<num><hundred>:ал1начӏит1
алӏна<num><hundred>:ал1начIитӏ
алӏна<num><hundred>:ал1начIитI
алӏна<num><hundred>:ал1начIит1
алӏна<num><hundred>:ал1нач1итӏ
алӏна<num><hundred>:ал1нач1итI
алӏна<num><hundred>:ал1нач1ит1
алӏна<num><part>:ал1нана
алӏна<num><ord>:ал1нас
алӏна<num><ten>:ал1найиг
акӏойо<adj><abs.pl>:акӏоа
акӏойо<adj><abs.pl>:акӏовā
акӏойо<adj><abs.pl>:акIоа
акӏойо<adj><abs.pl>:акIовā
акӏойо<adj><abs.pl>:ак1оа
акӏойо<adj><abs.pl>:ак1овā
абоц<n><pl><abs>:абоца
ацӏона<num><mult><part>:ацӏовахна
ацӏона<num><compord><abs>:ацӏонаийāлӏейо
ацӏона<num><compord><abs>:ацӏонаийāлIейо
ацӏона<num><compord><abs>:ацӏонаийāл1ейо
ацӏона<num><part>:ацӏонана
ацӏона<num><ord>:ацӏонас
ацӏона<num><mult><part>:ацIовахна
ацӏона<num><compord><abs>:ацIонаийāлӏейо
ацӏона<num><compord><abs>:ацIонаийāлIейо
ацӏона<num><compord><abs>:ацIонаийāл1ейо
ацӏона<num><part>:ацIонана
ацӏона<num><ord>:ацIонас
ацӏона<num><mult><part>:ац1овахна
ацӏона<num><compord><abs>:ац1онаийāлӏейо
ацӏона<num><compord><abs>:ац1онаийāлIейо
ацӏона<num><compord><abs>:ац1онаийāл1ейо
ацӏона<num><part>:ац1онана
ацӏона<num><ord>:ац1онас
аваданаб<adj><obl.sg>:аваданабли
аваданаб<adj><obl.pl>:аваданабла
аслийаб<adj><abs.pl>:аслийабла
аслийаб<adj><abs.pl>:аслийабла
аслийаб<adj><abs.pl>:аслиябла
аькаьлаьб<adj><abs.pl>:аькаьлаьблаь
аьчӏена<num><mult><part>:аьчӏейахна
аьчӏена<num><mult><part>:аьчӏейахна
аьчӏена<num><compord><abs>:аьчӏенаийāлӏейо
аьчӏена<num><compord><abs>:аьчӏенаийāлIейо
аьчӏена<num><compord><abs>:аьчӏенаийāл1ейо
аьчӏена<num><hundred>:аьчӏеначӏитӏ
аьчӏена<num><hundred>:аьчӏеначӏитI
аьчӏена<num><hundred>:аьчӏеначӏит1
аьчӏена<num><hundred>:аьчӏеначIитӏ
аьчӏена<num><hundred>:аьчӏеначIитI
аьчӏена<num><hundred>:аьчӏеначIит1
аьчӏена<num><hundred>:аьчӏенач1итӏ
аьчӏена<num><hundred>:аьчӏенач1итI
аьчӏена<num><hundred>:аьчӏенач1ит1
аьчӏена<num><part>:аьчӏенана
аьчӏена<num><ord>:аьчӏенас
аьчӏена<num><ten>:аьчӏенайиг
аьчӏена<num><mult><part>:аьчӏеяхна
аьчӏена<num><mult><part>:аьчIейахна
аьчӏена<num><mult><part>:аьчIейахна
аьчӏена<num><compord><abs>:аьчIенаийāлӏейо
аьчӏена<num><compord><abs>:аьчIенаийāлIейо
аьчӏена<num><compord><abs>:аьчIенаийāл1ейо
аьчӏена<num><hundred>:аьчIеначӏитӏ
аьчӏена<num><hundred>:аьчIеначӏитI
аьчӏена<num><hundred>:аьчIеначӏит1
аьчӏена<num><hundred>:аьчIеначIитӏ
аьчӏена<num><hundred>:аьчIеначIитI
аьчӏена<num><hundred>:аьчIеначIит1
аьчӏена<num><hundred>:аьчIенач1итӏ
аьчӏена<num><hundred>:аьчIенач1итI
аьчӏена<num><hundred>:аьчIенач1ит1
аьчӏена<num><part>:аьчIенана
аьчӏена<num><ord>:аьчIенас
аьчӏена<num><ten>:аьчIенайиг
аьчӏена<num><mult><part>:аьчIеяхна
аьчӏена<num><mult><part>:аьч1ейахна
аьчӏена<num><mult><part>:аьч1ейахна
аьчӏена<num><compord><abs>:аьч1енаийāлӏейо
аьчӏена<num><compord><abs>:аьч1енаийāлIейо
аьчӏена<num><compord><abs>:аьч1енаийāл1ейо
аьчӏена<num><hundred>:аьч1еначӏитӏ
аьчӏена<num><hundred>:аьч1еначӏитI
аьчӏена<num><hundred>:аьч1еначӏит1
аьчӏена<num><hundred>:аьч1еначIитӏ
аьчӏена<num><hundred>:аьч1еначIитI
аьчӏена<num><hundred>:аьч1еначIит1
аьчӏена<num><hundred>:аьч1енач1итӏ
аьчӏена<num><hundred>:аьч1енач1итI
аьчӏена<num><hundred>:аьч1енач1ит1
аьчӏена<num><part>:аьч1енана
аьчӏена<num><ord>:аьч1енас
аьчӏена<num><ten>:аьч1енайиг
аьчӏена<num><mult><part>:аьч1еяхна
тӏиган<n><pl><abs>:тӏигалла
тӏиган<n><pl><abs>:тӏиганла
тӏиган<n><pl><abs>:тIигалла
тӏиган<n><pl><abs>:тIиганла
тӏиган<n><pl><abs>:т1игалла
тӏиган<n><pl><abs>:т1иганла
илъна<num><compord><abs>:илънаийāлӏейо
илъна<num><compord><erg>:илънаийāлӏейа
илъна<num><compord><genI>:илънаийāлӏейас
илъна<num><compord><erg>:илънаийāлӏейа
илъна<num><compord><genI>:илънаийāлӏейас
илъна<num><compord><erg>:илънаийāлӏея
илъна<num><compord><genI>:илънаийāлӏеяс
илъна<num><compord><abs>:илънаийāлIейо
илъна<num><compord><erg>:илънаийāлIейа
илъна<num><compord><genI>:илънаийāлIейас
илъна<num><compord><erg>:илънаийāлIейа
илъна<num><compord><genI>:илънаийāлIейас
илъна<num><compord><erg>:илънаийāлIея
илъна<num><compord><genI>:илънаийāлIеяс
илъна<num><compord><abs>:илънаийāл1ейо
илъна<num><compord><erg>:илънаийāл1ейа
илъна<num><compord><genI>:илънаийāл1ейас
илъна<num><compord><erg>:илънаийāл1ейа
илъна<num><compord><genI>:илънаийāл1ейас
илъна<num><compord><erg>:илънаийāл1ея
илъна<num><compord><genI>:илънаийāл1еяс
илъна<num><hundred>:илъначӏитӏ
илъна<num><hundred>:илъначӏитI
илъна<num><hundred>:илъначӏит1
илъна<num><hundred>:илъначIитӏ
илъна<num><hundred>:илъначIитI
илъна<num><hundred>:илъначIит1
илъна<num><hundred>:илънач1итӏ
илъна<num><hundred>:илънач1итI
илъна<num><hundred>:илънач1ит1
илъна<num><part>:илънана
илъна<num><ord>:илънас
илъна<num><ten>:илънайиг
илъна<num><ten><obl><dat>:илънайиглал
илъна<num><ten><obl><genI>:илънайиглас
илъна<num><ten><obl><genII>:илънайиглала
илъна<num><ten><obl><ins>:илънайиглад
илъна<num><ten><obl><erg>:илънайигла
илъна<num><mult><part>:илъейахна
илъна<num><mult><part>:илъейахна
илъна<num><mult><part>:илъеяхна
иле<pron><obl><dat>:илол
иле<pron><obl><genI>:илос
иле<pron><obl><ins>:илод
иле<pron><abs>:иле
иле<pron><erg>:иле
иле<pron><obl><genII>:илла
ичӏей<n><pl><abs>:ичӏеййа
ичӏей<n><pl><abs>:ичӏеййа
ичӏей<n><pl><abs>:ичӏейба
ичӏей<n><pl><abs>:ичӏейя
ичӏей<n><pl><abs>:ичIеййа
ичӏей<n><pl><abs>:ичIеййа
ичӏей<n><pl><abs>:ичIейба
ичӏей<n><pl><abs>:ичIейя
ичӏей<n><pl><abs>:ич1еййа
ичӏей<n><pl><abs>:ич1еййа
ичӏей<n><pl><abs>:ич1ейба
ичӏей<n><pl><abs>:ич1ейя
оьл<v><inf>:оьлаьл
оьл<v><pst>:оьлийо
оьл<v><pst>:оьллоь
оьᴴкъоьнаь<num><mult><part>:оьᴴкъоьваьхна
оьᴴкъоьнаь<num><compord><abs>:оьᴴкъоьнаьийāлӏейо
оьᴴкъоьнаь<num><compord><abs>:оьᴴкъоьнаьийāлIейо
оьᴴкъоьнаь<num><compord><abs>:оьᴴкъоьнаьийāл1ейо
оьᴴкъоьнаь<num><hundred>:оьᴴкъоьнаьчӏитӏ
оьᴴкъоьнаь<num><hundred>:оьᴴкъоьнаьчӏитI
оьᴴкъоьнаь<num><hundred>:оьᴴкъоьнаьчӏит1
оьᴴкъоьнаь<num><hundred>:оьᴴкъоьнаьчIитӏ
оьᴴкъоьнаь<num><hundred>:оьᴴкъоьнаьчIитI
оьᴴкъоьнаь<num><hundred>:оьᴴкъоьнаьчIит1
оьᴴкъоьнаь<num><hundred>:оьᴴкъоьнаьч1итӏ
оьᴴкъоьнаь<num><hundred>:оьᴴкъоьнаьч1итI
оьᴴкъоьнаь<num><hundred>:оьᴴкъоьнаьч1ит1
оьᴴкъоьнаь<num><ord>:оьᴴкъоьнаьш
<II>атӏийо<pron><obl><dat>:йатӏийал
<II>атӏийо<pron><obl><genI>:йатӏийас
<II>атӏийо<pron><obl><genII>:йатӏийала
<II>атӏийо<pron><obl><ins>:йатӏийад
<II>атӏийо<pron><obl><sup><ess>:йатӏийакьа
<II>атӏийо<pron><obl><erg>:йатӏийа
<II>атӏийо<pron><abs>:йатӏийо
<II>атӏийо<pron><obl><dat>:йатӏийал
<II>атӏийо<pron><obl><genI>:йатӏийас
<II>атӏийо<pron><obl><genII>:йатӏийала
<II>атӏийо<pron><obl><ins>:йатӏийад
<II>атӏийо<pron><obl><sup><ess>:йатӏийакьа
<II>атӏийо<pron><obl><erg>:йатӏийа
<II>атӏийо<pron><obl><dat>:йатӏиял
<II>атӏийо<pron><obl><genI>:йатӏияс
<II>атӏийо<pron><obl><genII>:йатӏияла
<II>атӏийо<pron><obl><ins>:йатӏияд
<II>атӏийо<pron><obl><sup><ess>:йатӏиякьа
<II>атӏийо<pron><obl><erg>:йатӏия
<II>атӏийо<pron><obl><dat>:йатIийал
<II>атӏийо<pron><obl><genI>:йатIийас
<II>атӏийо<pron><obl><genII>:йатIийала
<II>атӏийо<pron><obl><ins>:йатIийад
<II>атӏийо<pron><obl><sup><ess>:йатIийакьа
<II>атӏийо<pron><obl><erg>:йатIийа
<II>атӏийо<pron><abs>:йатIийо
<II>атӏийо<pron><obl><dat>:йатIийал
<II>атӏийо<pron><obl><genI>:йатIийас
<II>атӏийо<pron><obl><genII>:йатIийала
<II>атӏийо<pron><obl><ins>:йатIийад
<II>атӏийо<pron><obl><sup><ess>:йатIийакьа
<II>атӏийо<pron><obl><erg>:йатIийа
<II>атӏийо<pron><obl><dat>:йатIиял
<II>атӏийо<pron><obl><genI>:йатIияс
<II>атӏийо<pron><obl><genII>:йатIияла
<II>атӏийо<pron><obl><ins>:йатIияд
<II>атӏийо<pron><obl><sup><ess>:йатIиякьа
<II>атӏийо<pron><obl><erg>:йатIия
<II>атӏийо<pron><obl><dat>:йат1ийал
<II>атӏийо<pron><obl><genI>:йат1ийас
<II>атӏийо<pron><obl><genII>:йат1ийала
<II>атӏийо<pron><obl><ins>:йат1ийад
<II>атӏийо<pron><obl><sup><ess>:йат1ийакьа
<II>атӏийо<pron><obl><erg>:йат1ийа
<II>атӏийо<pron><abs>:йат1ийо
<II>атӏийо<pron><obl><dat>:йат1ийал
<II>атӏийо<pron><obl><genI>:йат1ийас
<II>атӏийо<pron><obl><genII>:йат1ийала
<II>атӏийо<pron><obl><ins>:йат1ийад
<II>атӏийо<pron><obl><sup><ess>:йат1ийакьа
<II>атӏийо<pron><obl><erg>:йат1ийа
<II>атӏийо<pron><obl><dat>:йат1иял
<II>атӏийо<pron><obl><genI>:йат1ияс
<II>атӏийо<pron><obl><genII>:йат1ияла
<II>атӏийо<pron><obl><ins>:йат1ияд
<II>атӏийо<pron><obl><sup><ess>:йат1иякьа
<II>атӏийо<pron><obl><erg>:йат1ия
<II>угъо<v><imp><prmI>:йугъала
<II>угъо<v><imp><prmI><prmII>:йугъалаъ
<II>укъо<adj><abs.sg>:йукъо
<II>укъо<adj><obl.sg><dat>:йукъал
<II>укъо<adj><obl.sg><genI>:йукъас
<II>укъо<adj><obl.sg><genII>:йукъала
<II>укъо<adj><obl.sg><ins>:йукъад
<II>укъо<adj><obl.sg><erg>:йукъа
<II>атӏийо<pron><obl><dat>:йатӏийал
<II>атӏийо<pron><obl><genI>:йатӏийас
<II>атӏийо<pron><obl><genII>:йатӏийала
<II>атӏийо<pron><obl><ins>:йатӏийад
<II>атӏийо<pron><obl><sup><ess>:йатӏийакьа
<II>атӏийо<pron><obl><erg>:йатӏийа
<II>атӏийо<pron><abs>:йатӏийо
<II>атӏийо<pron><obl><dat>:йатӏийал
<II>атӏийо<pron><obl><genI>:йатӏийас
<II>атӏийо<pron><obl><genII>:йатӏийала
<II>атӏийо<pron><obl><ins>:йатӏийад
<II>атӏийо<pron><obl><sup><ess>:йатӏийакьа
<II>атӏийо<pron><obl><erg>:йатӏийа
<II>атӏийо<pron><obl><dat>:йатӏиял
<II>атӏийо<pron><obl><genI>:йатӏияс
<II>атӏийо<pron><obl><genII>:йатӏияла
<II>атӏийо<pron><obl><ins>:йатӏияд
<II>атӏийо<pron><obl><sup><ess>:йатӏиякьа
<II>атӏийо<pron><obl><erg>:йатӏия
<II>атӏийо<pron><obl><dat>:йатIийал
<II>атӏийо<pron><obl><genI>:йатIийас
<II>атӏийо<pron><obl><genII>:йатIийала
<II>атӏийо<pron><obl><ins>:йатIийад
<II>атӏийо<pron><obl><sup><ess>:йатIийакьа
<II>атӏийо<pron><obl><erg>:йатIийа
<II>атӏийо<pron><abs>:йатIийо
<II>атӏийо<pron><obl><dat>:йатIийал
<II>атӏийо<pron><obl><genI>:йатIийас
<II>атӏийо<pron><obl><genII>:йатIийала
<II>атӏийо<pron><obl><ins>:йатIийад
<II>атӏийо<pron><obl><sup><ess>:йатIийакьа
<II>атӏийо<pron><obl><erg>:йатIийа
<II>атӏийо<pron><obl><dat>:йатIиял
<II>атӏийо<pron><obl><genI>:йатIияс
<II>атӏийо<pron><obl><genII>:йатIияла
<II>атӏийо<pron><obl><ins>:йатIияд
<II>атӏийо<pron><obl><sup><ess>:йатIиякьа
<II>атӏийо<pron><obl><erg>:йатIия
<II>атӏийо<pron><obl><dat>:йат1ийал
<II>атӏийо<pron><obl><genI>:йат1ийас
<II>атӏийо<pron><obl><genII>:йат1ийала
<II>атӏийо<pron><obl><ins>:йат1ийад
<II>атӏийо<pron><obl><sup><ess>:йат1ийакьа
<II>атӏийо<pron><obl><erg>:йат1ийа
<II>атӏийо<pron><abs>:йат1ийо
<II>атӏийо<pron><obl><dat>:йат1ийал
<II>атӏийо<pron><obl><genI>:йат1ийас
<II>атӏийо<pron><obl><genII>:йат1ийала
<II>атӏийо<pron><obl><ins>:йат1ийад
<II>атӏийо<pron><obl><sup><ess>:йат1ийакьа
<II>атӏийо<pron><obl><erg>:йат1ийа
<II>атӏийо<pron><obl><dat>:йат1иял
<II>атӏийо<pron><obl><genI>:йат1ияс
<II>атӏийо<pron><obl><genII>:йат1ияла
<II>атӏийо<pron><obl><ins>:йат1ияд
<II>атӏийо<pron><obl><sup><ess>:йат1иякьа
<II>атӏийо<pron><obl><erg>:йат1ия
<II>атӏийо<pron><obl><dat>:ятӏийал
<II>атӏийо<pron><obl><genI>:ятӏийас
<II>атӏийо<pron><obl><genII>:ятӏийала
<II>атӏийо<pron><obl><ins>:ятӏийад
<II>атӏийо<pron><obl><sup><ess>:ятӏийакьа
<II>атӏийо<pron><obl><erg>:ятӏийа
<II>атӏийо<pron><abs>:ятӏийо
<II>атӏийо<pron><obl><dat>:ятӏийал
<II>атӏийо<pron><obl><genI>:ятӏийас
<II>атӏийо<pron><obl><genII>:ятӏийала
<II>атӏийо<pron><obl><ins>:ятӏийад
<II>атӏийо<pron><obl><sup><ess>:ятӏийакьа
<II>атӏийо<pron><obl><erg>:ятӏийа
<II>атӏийо<pron><obl><dat>:ятӏиял
<II>атӏийо<pron><obl><genI>:ятӏияс
<II>атӏийо<pron><obl><genII>:ятӏияла
<II>атӏийо<pron><obl><ins>:ятӏияд
<II>атӏийо<pron><obl><sup><ess>:ятӏиякьа
<II>атӏийо<pron><obl><erg>:ятӏия
<II>атӏийо<pron><obl><dat>:ятIийал
<II>атӏийо<pron><obl><genI>:ятIийас
<II>атӏийо<pron><obl><genII>:ятIийала
<II>атӏийо<pron><obl><ins>:ятIийад
<II>атӏийо<pron><obl><sup><ess>:ятIийакьа
<II>атӏийо<pron><obl><erg>:ятIийа
<II>атӏийо<pron><abs>:ятIийо
<II>атӏийо<pron><obl><dat>:ятIийал
<II>атӏийо<pron><obl><genI>:ятIийас
<II>атӏийо<pron><obl><genII>:ятIийала
<II>атӏийо<pron><obl><ins>:ятIийад
<II>атӏийо<pron><obl><sup><ess>:ятIийакьа
<II>атӏийо<pron><obl><erg>:ятIийа
<II>атӏийо<pron><obl><dat>:ятIиял
<II>атӏийо<pron><obl><genI>:ятIияс
<II>атӏийо<pron><obl><genII>:ятIияла
<II>атӏийо<pron><obl><ins>:ятIияд
<II>атӏийо<pron><obl><sup><ess>:ятIиякьа
<II>атӏийо<pron><obl><erg>:ятIия
<II>атӏийо<pron><obl><dat>:ят1ийал
<II>атӏийо<pron><obl><genI>:ят1ийас
<II>атӏийо<pron><obl><genII>:ят1ийала
<II>атӏийо<pron><obl><ins>:ят1ийад
<II>атӏийо<pron><obl><sup><ess>:ят1ийакьа
<II>атӏийо<pron><obl><erg>:ят1ийа
<II>атӏийо<pron><abs>:ят1ийо
<II>атӏийо<pron><obl><dat>:ят1ийал
<II>атӏийо<pron><obl><genI>:ят1ийас
<II>атӏийо<pron><obl><genII>:ят1ийала
<II>атӏийо<pron><obl><ins>:ят1ийад
<II>атӏийо<pron><obl><sup><ess>:ят1ийакьа
<II>атӏийо<pron><obl><erg>:ят1ийа
<II>атӏийо<pron><obl><dat>:ят1иял
<II>атӏийо<pron><obl><genI>:ят1ияс
<II>атӏийо<pron><obl><genII>:ят1ияла
<II>атӏийо<pron><obl><ins>:ят1ияд
<II>атӏийо<pron><obl><sup><ess>:ят1иякьа
<II>атӏийо<pron><obl><erg>:ят1ия
лӏаьммоь<adj><abs.sg><emp>:лӏаьммоьсо
лӏаьммоь<adj><abs.sg><emp>:лӏаьммоьшоь
лӏаьммоь<adj><abs.sg><emp>:лIаьммоьсо
лӏаьммоь<adj><abs.sg><emp>:лIаьммоьшоь
лӏаьммоь<adj><abs.sg><emp>:л1аьммоьсо
лӏаьммоь<adj><abs.sg><emp>:л1аьммоьшоь
лъана<num><compord><abs>:лъанаийāлӏейо
лъана<num><compord><abs>:лъанаийāлIейо
лъана<num><compord><abs>:лъанаийāл1ейо
лъана<num><hundred>:лъаначӏитӏ
лъана<num><hundred>:лъаначӏитI
лъана<num><hundred>:лъаначӏит1
лъана<num><hundred>:лъаначIитӏ
лъана<num><hundred>:лъаначIитI
лъана<num><hundred>:лъаначIит1
лъана<num><hundred>:лъанач1итӏ
лъана<num><hundred>:лъанач1итI
лъана<num><hundred>:лъанач1ит1
лъана<num><part>:лъанана
лъана<num><ord>:лъанас
лъана<num><ten>:лъанайиг
лъана<num><abs>:лъана
лъана<num><obl><dat>:лъанил
лъана<num><obl><genI>:лъанис
лъана<num><obl><genII>:лъанила
лъана<num><obl><ins>:лъанид
лъана<num><obl><erg>:лъани
лъана<num><mult><part>:лъахна
лъина<num><mult><part>:лъийахна
лъина<num><mult><part>:лъийахна
лъина<num><compord><abs>:лъинаийāлӏейо
лъина<num><compord><abs>:лъинаийāлIейо
лъина<num><compord><abs>:лъинаийāл1ейо
лъина<num><hundred>:лъиначӏитӏ
лъина<num><hundred><obl><dat>:лъиначӏитӏлал
лъина<num><hundred><obl><genI>:лъиначӏитӏлас
лъина<num><hundred><obl><genII>:лъиначӏитӏлала
лъина<num><hundred><obl><ins>:лъиначӏитӏлад
лъина<num><hundred><obl><erg>:лъиначӏитӏла
лъина<num><hundred>:лъиначӏитI
лъина<num><hundred><obl><dat>:лъиначӏитIлал
лъина<num><hundred><obl><genI>:лъиначӏитIлас
лъина<num><hundred><obl><genII>:лъиначӏитIлала
лъина<num><hundred><obl><ins>:лъиначӏитIлад
лъина<num><hundred><obl><erg>:лъиначӏитIла
лъина<num><hundred>:лъиначӏит1
лъина<num><hundred><obl><dat>:лъиначӏит1лал
лъина<num><hundred><obl><genI>:лъиначӏит1лас
лъина<num><hundred><obl><genII>:лъиначӏит1лала
лъина<num><hundred><obl><ins>:лъиначӏит1лад
лъина<num><hundred><obl><erg>:лъиначӏит1ла
лъина<num><hundred>:лъиначIитӏ
лъина<num><hundred><obl><dat>:лъиначIитӏлал
лъина<num><hundred><obl><genI>:лъиначIитӏлас
лъина<num><hundred><obl><genII>:лъиначIитӏлала
лъина<num><hundred><obl><ins>:лъиначIитӏлад
лъина<num><hundred><obl><erg>:лъиначIитӏла
лъина<num><hundred>:лъиначIитI
лъина<num><hundred><obl><dat>:лъиначIитIлал
лъина<num><hundred><obl><genI>:лъиначIитIлас
лъина<num><hundred><obl><genII>:лъиначIитIлала
лъина<num><hundred><obl><ins>:лъиначIитIлад
лъина<num><hundred><obl><erg>:лъиначIитIла
лъина<num><hundred>:лъиначIит1
лъина<num><hundred><obl><dat>:лъиначIит1лал
лъина<num><hundred><obl><genI>:лъиначIит1лас
лъина<num><hundred><obl><genII>:лъиначIит1лала
лъина<num><hundred><obl><ins>:лъиначIит1лад
лъина<num><hundred><obl><erg>:лъиначIит1ла
лъина<num><hundred>:лъинач1итӏ
лъина<num><hundred><obl><dat>:лъинач1итӏлал
лъина<num><hundred><obl><genI>:лъинач1итӏлас
лъина<num><hundred><obl><genII>:лъинач1итӏлала
лъина<num><hundred><obl><ins>:лъинач1итӏлад
лъина<num><hundred><obl><erg>:лъинач1итӏла
лъина<num><hundred>:лъинач1итI
лъина<num><hundred><obl><dat>:лъинач1итIлал
лъина<num><hundred><obl><genI>:лъинач1итIлас
лъина<num><hundred><obl><genII>:лъинач1итIлала
лъина<num><hundred><obl><ins>:лъинач1итIлад
лъина<num><hundred><obl><erg>:лъинач1итIла
лъина<num><hundred>:лъинач1ит1
лъина<num><hundred><obl><dat>:лъинач1ит1лал
лъина<num><hundred><obl><genI>:лъинач1ит1лас
лъина<num><hundred><obl><genII>:лъинач1ит1лала
лъина<num><hundred><obl><ins>:лъинач1ит1лад
лъина<num><hundred><obl><erg>:лъинач1ит1ла
лъина<num><part>:лъинана
лъина<num><ord>:лъинас
лъина<num><ord><obl><dat>:лъинаслил
лъина<num><ord><obl><genI>:лъинаслис
лъина<num><ord><obl><genII>:лъинаслила
лъина<num><ord><obl><ins>:лъинаслид
лъина<num><ord><obl><erg>:лъинасли
лъина<num><ten>:лъинайиг
лъина<num><mult><part>:лъияхна
гаьммоь<adj><abs.pl>:гаьммāь
гъаьгъаьтӏоь<adj><abs.sg>:гъаьгъаьтӏоь
гъаьгъаьтӏоь<adj><obl.sg>:гъаьгъаьтӏаь
гъаьгъаьтӏоь<adj><obl.pl>:гъаьгъаьтӏāь
гъаьгъаьтӏоь<adj><abs.pl>:гъаьгъаьтӏāь
гъаьгъаьтӏоь<adj><abs.sg>:гъаьгъаьтIоь
гъаьгъаьтӏоь<adj><obl.sg>:гъаьгъаьтIаь
гъаьгъаьтӏоь<adj><obl.pl>:гъаьгъаьтIāь
гъаьгъаьтӏоь<adj><abs.pl>:гъаьгъаьтIāь
гъаьгъаьтӏоь<adj><abs.sg>:гъаьгъаьт1оь
гъаьгъаьтӏоь<adj><obl.sg>:гъаьгъаьт1аь
гъаьгъаьтӏоь<adj><obl.pl>:гъаьгъаьт1āь
гъаьгъаьтӏоь<adj><abs.pl>:гъаьгъаьт1āь
гьасагъас<adj><abs.pl>:гьасагъаса
гьасагъас<adj><abs.pl>:гьасагъасвā
гьасагъас<adj><abs.pl>:гьасагъасā
гьоᴴс<num><mult>:гьаᴴкъкъа
гьо<dem><med><II/III><obl.pl><dat>:гьоллол
гьо<dem><med><II/III><obl.pl><genI>:гьоллос
гьо<dem><med><II/III><obl.pl><genII>:гьоллола
гьо<dem><med><II/III><obl.pl><ins>:гьоллод
гьо<dem><med><II/III><obl.pl><erg>:гьолло
гьо<dem><med><II/III><obl><dat>:гьоллъол
гьо<dem><med><II/III><obl><genI>:гьоллъос
гьо<dem><med><II/III><obl><genII>:гьоллъола
гьо<dem><med><II/III><obl><ins>:гьоллъод
гьо<dem><med><II/III><obl><erg>:гьоллъо
гьо<dem><med><II/III><pl><abs>:гьоллōл
гьо<dem><med><II/III><obl><dat>:гьолълъол
гьо<dem><med><II/III><obl><genI>:гьолълъос
гьо<dem><med><II/III><obl><genII>:гьолълъола
гьо<dem><med><II/III><obl><ins>:гьолълъод
гьо<dem><med><II/III><obl><erg>:гьолълъо
гьо<dem><prox><II/III><obl><dat>:гьолӏол
гьо<dem><prox><II/III><obl><genI>:гьолӏос
гьо<dem><prox><II/III><obl><genII>:гьолӏола
гьо<dem><prox><II/III><obl><ins>:гьолӏод
гьо<dem><prox><II/III><obl><erg>:гьолӏо
гьо<dem><prox><II/III><obl><dat>:гьолIол
гьо<dem><prox><II/III><obl><genI>:гьолIос
гьо<dem><prox><II/III><obl><genII>:гьолIола
гьо<dem><prox><II/III><obl><ins>:гьолIод
гьо<dem><prox><II/III><obl><erg>:гьолIо
гьо<dem><prox><II/III><obl><dat>:гьол1ол
гьо<dem><prox><II/III><obl><genI>:гьол1ос
гьо<dem><prox><II/III><obl><genII>:гьол1ола
гьо<dem><prox><II/III><obl><ins>:гьол1од
гьо<dem><prox><II/III><obl><erg>:гьол1о
гьо<dem><dist><II/III><obl><dat>:гьоглӏол
гьо<dem><dist><II/III><obl><genI>:гьоглӏос
гьо<dem><dist><II/III><obl><genII>:гьоглӏола
гьо<dem><dist><II/III><obl><ins>:гьоглӏод
гьо<dem><dist><II/III><obl><erg>:гьоглӏо
гьо<dem><dist><II/III><obl.pl><dat>:гьоглол
гьо<dem><dist><II/III><obl.pl><genI>:гьоглос
гьо<dem><dist><II/III><obl.pl><genII>:гьоглола
гьо<dem><dist><II/III><obl.pl><ins>:гьоглод
гьо<dem><dist><II/III><obl.pl><erg>:гьогло
гьо<dem><dist><II/III><obl><dat>:гьоглIол
гьо<dem><dist><II/III><obl><genI>:гьоглIос
гьо<dem><dist><II/III><obl><genII>:гьоглIола
гьо<dem><dist><II/III><obl><ins>:гьоглIод
гьо<dem><dist><II/III><obl><erg>:гьоглIо
гьо<dem><dist><II/III><obl><dat>:гьогл1ол
гьо<dem><dist><II/III><obl><genI>:гьогл1ос
гьо<dem><dist><II/III><obl><genII>:гьогл1ола
гьо<dem><dist><II/III><obl><ins>:гьогл1од
гьо<dem><dist><II/III><obl><erg>:гьогл1о
гьо<dem><dist><II/III><pl><abs>:гьоггōл
гьо<dem><prox><II/III><obl.pl><dat>:гьодлол
гьо<dem><prox><II/III><obl.pl><genI>:гьодлос
гьо<dem><prox><II/III><obl.pl><genII>:гьодлола
гьо<dem><prox><II/III><obl.pl><ins>:гьодлод
гьо<dem><prox><II/III><obl.pl><erg>:гьодло
гьо<dem><prox><II/III><pl><abs>:гьоддōл
гьоᴴс<num><compord><abs>:гьоᴴсийāлӏейо
гьоᴴс<num><compord><abs>:гьоᴴсийāлIейо
гьоᴴс<num><compord><abs>:гьоᴴсийāл1ейо
гьоᴴс<num><hundred>:гьоᴴсчӏитӏ
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчӏитӏйах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчӏитӏйах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчӏитӏях
гьоᴴс<num><hundred>:гьоᴴсчӏитI
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчӏитIйах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчӏитIйах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчӏитIях
гьоᴴс<num><hundred>:гьоᴴсчӏит1
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчӏит1йах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчӏит1йах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчӏит1ях
гьоᴴс<num><hundred>:гьоᴴсчIитӏ
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчIитӏйах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчIитӏйах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчIитӏях
гьоᴴс<num><hundred>:гьоᴴсчIитI
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчIитIйах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчIитIйах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчIитIях
гьоᴴс<num><hundred>:гьоᴴсчIит1
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчIит1йах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчIит1йах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчIит1ях
гьоᴴс<num><hundred>:гьоᴴсч1итӏ
гьоᴴс<num><hundred><inf><mult>:гьоᴴсч1итӏйах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсч1итӏйах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсч1итӏях
гьоᴴс<num><hundred>:гьоᴴсч1итI
гьоᴴс<num><hundred><inf><mult>:гьоᴴсч1итIйах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсч1итIйах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсч1итIях
гьоᴴс<num><hundred>:гьоᴴсч1ит1
гьоᴴс<num><hundred><inf><mult>:гьоᴴсч1ит1йах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсч1ит1йах
гьоᴴс<num><hundred><inf><mult>:гьоᴴсч1ит1ях
гьоᴴс<num><abs>:гьоᴴс
гьу<dem><med><I/IV><obl><dat>:гьолцол
гьу<dem><med><I/IV><obl><genI>:гьолцос
гьу<dem><med><I/IV><obl><genII>:гьолцола
гьу<dem><med><I/IV><obl><genII><cont><ess><lat>:гьолцолалъил
гьу<dem><med><I/IV><obl><genII><in><ess><lat>:гьолцолаъал
гьу<dem><med><I/IV><obl><ins>:гьолцод
гьу<dem><med><I/IV><obl><sup><ess><dir><transl>:гьолцокьадāкьā
гьу<dem><med><I/IV><obl><sup><ess><transl>:гьолцокьалкьā
гьу<dem><med><I/IV><obl><cont><ess><genII><lat>:гьолцолълал
гьу<dem><med><I/IV><obl><cont><ess><lat>:гьолцолъил
гьу<dem><med><I/IV><obl><cont><ess><abl>:гьолцолъсо
гьу<dem><med><I/IV><obl><in><ess><abl>:гьолцоъос
гьу<dem><med><I/IV><obl><in><ess><lat>:гьолцоъол
гьу<dem><med><I/IV><obl><erg>:гьолцо
гьу<dem><dist><I/IV><obl><dat>:гьогцол
гьу<dem><dist><I/IV><obl><genI>:гьогцос
гьу<dem><dist><I/IV><obl><genII>:гьогцола
гьу<dem><dist><I/IV><obl><ins>:гьогцод
гьу<dem><dist><I/IV><obl><erg>:гьогцо
гьу<dem><prox><I/IV><obl><dat>:гьоцол
гьу<dem><prox><I/IV><obl><genI>:гьоцос
гьу<dem><prox><I/IV><obl><genII>:гьоцола
гьу<dem><prox><I/IV><obl><ins>:гьоцод
гьу<dem><prox><I/IV><obl><erg>:гьоцо
г<m>л<v><inf>:голал
г<nh>л<v><imp><prmI><prmII>:гулалаъ
г<nh>л<v><cond><cnc>:гулдана
г<nh>л<v><cond><invc>:гулдал
г<nh>л<v><neg><prs>:гулаъас
г<nh>л<v><opt>:гулакъос
г<nh>л<v><opt>:гулкъос
г<nh>л<v><proh>:гулāкъа
г<nh>л<v><pst><irr>:гулийокъодā
г<nh>л<v><pst><irr>:гуллокъодā
г<nh>л<v><prs><irr>:гулцакъодā
гьоᴴс<num><obl><dat>:сидил
гьоᴴс<num><obl><genI>:сидис
гьоᴴс<num><obl><genII>:сидила
гьоᴴс<num><obl><ins>:сидид
гьоᴴс<num><obl><sub><ess>:сидилӏ
гьоᴴс<num><obl><sub><ess><genII>:сидилӏла
гьоᴴс<num><obl><sub><ess><genII><lat>:сидилӏлал
гьоᴴс<num><obl><sub><ess><genII><transl>:сидилӏлакьā
гьоᴴс<num><obl><sub><ess><dir>:сидилӏдā
гьоᴴс<num><obl><sub><ess><dir><abl>:сидилӏдāс
гьоᴴс<num><obl><sub><ess><dir><lat>:сидилӏдāл
гьоᴴс<num><obl><sub><ess><dir><transl>:сидилӏдāкьā
гьоᴴс<num><obl><sub><ess><lat>:сидилӏил
гьоᴴс<num><obl><sub><ess><abl>:сидилӏсо
гьоᴴс<num><obl><sub><ess><transl>:сидилӏкьā
гьоᴴс<num><obl><sub><ess>:сидилI
гьоᴴс<num><obl><sub><ess><genII>:сидилIла
гьоᴴс<num><obl><sub><ess><genII><lat>:сидилIлал
гьоᴴс<num><obl><sub><ess><genII><transl>:сидилIлакьā
гьоᴴс<num><obl><sub><ess><dir>:сидилIдā
гьоᴴс<num><obl><sub><ess><dir><abl>:сидилIдāс
гьоᴴс<num><obl><sub><ess><dir><lat>:сидилIдāл
гьоᴴс<num><obl><sub><ess><dir><transl>:сидилIдāкьā
гьоᴴс<num><obl><sub><ess><lat>:сидилIил
гьоᴴс<num><obl><sub><ess><abl>:сидилIсо
гьоᴴс<num><obl><sub><ess><transl>:сидилIкьā
гьоᴴс<num><obl><sub><ess>:сидил1
гьоᴴс<num><obl><sub><ess><genII>:сидил1ла
гьоᴴс<num><obl><sub><ess><genII><lat>:сидил1лал
гьоᴴс<num><obl><sub><ess><genII><transl>:сидил1лакьā
гьоᴴс<num><obl><sub><ess><dir>:сидил1дā
гьоᴴс<num><obl><sub><ess><dir><abl>:сидил1дāс
гьоᴴс<num><obl><sub><ess><dir><lat>:сидил1дāл
гьоᴴс<num><obl><sub><ess><dir><transl>:сидил1дāкьā
гьоᴴс<num><obl><sub><ess><lat>:сидил1ил
гьоᴴс<num><obl><sub><ess><abl>:сидил1со
гьоᴴс<num><obl><sub><ess><transl>:сидил1кьā
гьоᴴс<num><obl><cont><ess>:сидилъ
гьоᴴс<num><obl><cont><ess><dir>:сидилъдā
гьоᴴс<num><obl><cont><ess><dir><abl>:сидилъдāс
гьоᴴс<num><obl><cont><ess><dir><lat>:сидилъдāл
гьоᴴс<num><obl><cont><ess><dir><transl>:сидилъдāкьā
гьоᴴс<num><obl><cont><ess><lat>:сидилъил
гьоᴴс<num><obl><cont><ess><abl>:сидилъсо
гьоᴴс<num><obl><cont><ess><transl>:сидилъкьā
гьоᴴс<num><obl><in><ess>:сидиъ
гьоᴴс<num><obl><in><ess><abl>:сидиъис
гьоᴴс<num><obl><in><ess><dir>:сидиъдā
гьоᴴс<num><obl><in><ess><dir><abl>:сидиъдāс
гьоᴴс<num><obl><in><ess><dir><lat>:сидиъдāл
гьоᴴс<num><obl><in><ess><dir><transl>:сидиъдāкьā
гьоᴴс<num><obl><in><ess><lat>:сидиъил
гьоᴴс<num><obl><in><ess><transl>:сидиъкьā
гьоᴴс<num><obl><erg>:сиди
гьоᴴс<num><genII><sup><ess>:сидлакьа
гьоᴴс<num><genII><sup><ess><abl>:сидлакьас
гьоᴴс<num><genII><sup><ess><lat>:сидлакьал
гьоᴴс<num><genII><ad><ess>:сидлагъа
гьоᴴс<num><genII><ad><ess><abl>:сидлагъас
гьоᴴс<num><genII><ad><ess><lat>:сидлагъал
гьоᴴс<num><genII><sub><ess>:сидлалӏ
гьоᴴс<num><genII><sub><ess><lat>:сидлалӏил
гьоᴴс<num><genII><sub><ess>:сидлалI
гьоᴴс<num><genII><sub><ess><lat>:сидлалIил
гьоᴴс<num><genII><sub><ess>:сидлал1
гьоᴴс<num><genII><sub><ess><lat>:сидлал1ил
гьоᴴс<num><sup><ess>:сидкьа
гьоᴴс<num><sup><ess><genII>:сидкьала
гьоᴴс<num><sup><ess><genII><abl>:сидкьалас
гьоᴴс<num><sup><ess><genII><lat>:сидкьалал
гьоᴴс<num><sup><ess><genII><transl>:сидкьалакьā
гьоᴴс<num><sup><ess><dir>:сидкьадā
гьоᴴс<num><sup><ess><dir><abl>:сидкьадāс
гьоᴴс<num><sup><ess><dir><lat>:сидкьадāл
гьоᴴс<num><sup><ess><dir><transl>:сидкьадāкьā
гьоᴴс<num><sup><ess><transl>:сидкьалкьā
гьоᴴс<num><sup><ess><abl>:сидкьас
гьоᴴс<num><sup><ess><lat>:сидкьал
гьоᴴс<num><ad><ess>:сидгъа
гьоᴴс<num><ad><ess><genII><abl>:сидгъалас
гьоᴴс<num><ad><ess><genII><lat>:сидгъалал
гьоᴴс<num><ad><ess><genII><transl>:сидгъалакьā
гьоᴴс<num><ad><ess><dir>:сидгъадā
гьоᴴс<num><ad><ess><dir><abl>:сидгъадāс
гьоᴴс<num><ad><ess><dir><lat>:сидгъадāл
гьоᴴс<num><ad><ess><dir><transl>:сидгъадāкьā
гьоᴴс<num><ad><ess><transl>:сидгъалкьā
гьоᴴс<num><ad><ess><abl>:сидгъас
гьоᴴс<num><ad><ess><lat>:сидгъал
гьоᴴс<num><apud><ess>:сиддой
гьоᴴс<num><apud><ess><dir>:сиддойдā
гьоᴴс<num><apud><ess><dir><abl>:сиддойдāс
гьоᴴс<num><apud><ess><dir><lat>:сиддойдāл
гьоᴴс<num><apud><ess><dir><transl>:сиддойдāкьā
гьоᴴс<num><apud><ess><abl>:сиддойс
гьоᴴс<num><apud><ess><lat>:сиддойл
гьоᴴс<num><apud><ess><transl>:сиддойкьā
гьоᴴс<num><cum><ess>:сидгъой
гьоᴴс<num><cum><ess><dir>:сидгъойдā
гьоᴴс<num><cum><ess><dir><abl>:сидгъойдāс
гьоᴴс<num><cum><ess><dir><lat>:сидгъойдāл
гьоᴴс<num><cum><ess><dir><transl>:сидгъойдāкьā
гьоᴴс<num><cum><ess><abl>:сидгъойс
гьоᴴс<num><cum><ess><lat>:сидгъойл
гьоᴴс<num><cum><ess><transl>:сидгъойкьā
гьоᴴс<num><poss><ess>:сидхъа
гьоᴴс<num><poss><ess><dir>:сидхъадā
гьоᴴс<num><poss><ess><dir><abl>:сидхъадāс
гьоᴴс<num><poss><ess><dir><lat>:сидхъадāл
гьоᴴс<num><poss><ess><dir><transl>:сидхъадāкьā
гьоᴴс<num><poss><ess><transl>:сидхъалкьā
гьоᴴс<num><poss><ess><abl>:сидхъас
гьоᴴс<num><poss><ess><lat>:сидхъал
кид<n><obl><genII>:киббала
къона<num><mult><part>:кӏахна
къаькъаьлоь<adj><abs.pl>:къаькъаьлāь
къона<num><compord><abs>:къонаийāлӏейо
къона<num><compord><abs>:къонаийāлIейо
къона<num><compord><abs>:къонаийāл1ейо
къона<num><hundred>:къоначӏитӏ
къона<num><hundred>:къоначӏитI
къона<num><hundred>:къоначӏит1
къона<num><hundred>:къоначIитӏ
къона<num><hundred>:къоначIитI
къона<num><hundred>:къоначIит1
къона<num><hundred>:къонач1итӏ
къона<num><hundred>:къонач1итI
къона<num><hundred>:къонач1ит1
къона<num><part>:къонана
къона<num><ord>:къонас
къона<num><mult><part>:кIахна
къона<num><mult><part>:к1ахна
<III>атӏийо<pron><obl><dat>:батӏийал
<III>атӏийо<pron><obl><genI>:батӏийас
<III>атӏийо<pron><obl><genII>:батӏийала
<III>атӏийо<pron><obl><ins>:батӏийад
<III>атӏийо<pron><obl><sup><ess>:батӏийакьа
<III>атӏийо<pron><obl><erg>:батӏийа
<III>атӏийо<pron><abs>:батӏийо
<III>атӏийо<pron><obl><dat>:батӏийал
<III>атӏийо<pron><obl><genI>:батӏийас
<III>атӏийо<pron><obl><genII>:батӏийала
<III>атӏийо<pron><obl><ins>:батӏийад
<III>атӏийо<pron><obl><sup><ess>:батӏийакьа
<III>атӏийо<pron><obl><erg>:батӏийа
<III>атӏийо<pron><obl><dat>:батӏиял
<III>атӏийо<pron><obl><genI>:батӏияс
<III>атӏийо<pron><obl><genII>:батӏияла
<III>атӏийо<pron><obl><ins>:батӏияд
<III>атӏийо<pron><obl><sup><ess>:батӏиякьа
<III>атӏийо<pron><obl><erg>:батӏия
<III>атӏийо<pron><obl><dat>:батIийал
<III>атӏийо<pron><obl><genI>:батIийас
<III>атӏийо<pron><obl><genII>:батIийала
<III>атӏийо<pron><obl><ins>:батIийад
<III>атӏийо<pron><obl><sup><ess>:батIийакьа
<III>атӏийо<pron><obl><erg>:батIийа
<III>атӏийо<pron><abs>:батIийо
<III>атӏийо<pron><obl><dat>:батIийал
<III>атӏийо<pron><obl><genI>:батIийас
<III>атӏийо<pron><obl><genII>:батIийала
<III>атӏийо<pron><obl><ins>:батIийад
<III>атӏийо<pron><obl><sup><ess>:батIийакьа
<III>атӏийо<pron><obl><erg>:батIийа
<III>атӏийо<pron><obl><dat>:батIиял
<III>атӏийо<pron><obl><genI>:батIияс
<III>атӏийо<pron><obl><genII>:батIияла
<III>атӏийо<pron><obl><ins>:батIияд
<III>атӏийо<pron><obl><sup><ess>:батIиякьа
<III>атӏийо<pron><obl><erg>:батIия
<III>атӏийо<pron><obl><dat>:бат1ийал
<III>атӏийо<pron><obl><genI>:бат1ийас
<III>атӏийо<pron><obl><genII>:бат1ийала
<III>атӏийо<pron><obl><ins>:бат1ийад
<III>атӏийо<pron><obl><sup><ess>:бат1ийакьа
<III>атӏийо<pron><obl><erg>:бат1ийа
<III>атӏийо<pron><abs>:бат1ийо
<III>атӏийо<pron><obl><dat>:бат1ийал
<III>атӏийо<pron><obl><genI>:бат1ийас
<III>атӏийо<pron><obl><genII>:бат1ийала
<III>атӏийо<pron><obl><ins>:бат1ийад
<III>атӏийо<pron><obl><sup><ess>:бат1ийакьа
<III>атӏийо<pron><obl><erg>:бат1ийа
<III>атӏийо<pron><obl><dat>:бат1иял
<III>атӏийо<pron><obl><genI>:бат1ияс
<III>атӏийо<pron><obl><genII>:бат1ияла
<III>атӏийо<pron><obl><ins>:бат1ияд
<III>атӏийо<pron><obl><sup><ess>:бат1иякьа
<III>атӏийо<pron><obl><erg>:бат1ия
<nhpl>угъо<v><pl><inf>:йугъоаал
<nhpl>угъо<v><pl><inf>:йугъойал
<nhpl>угъо<v><pl><inf>:йугъойал
<nhpl>угъо<v><pl><inf>:йугъобал
<nhpl>угъо<v><pl><inf>:йугъовал
<nhpl>угъо<v><pl><inf>:йугъоāл
<nhpl>угъо<v><pl><inf>:йугъоял
<refl>:жуь
<refl><pl>:жуьвōьл
<refl>:зу
<refl><pl>:зувōьл
<thousand><obl><dat>:гьазайлал
<thousand><obl><genI>:гьазайлас
<thousand><obl><genII>:гьазайлала
<thousand><obl><ins>:гьазайлад
<thousand><obl><erg>:гьазайла
бикдийо<adj><abs.pl>:бикдийā
бокьараб<pron><obl><dat>:бокьараблил
бокьараб<pron><obl><genI>:бокьараблис
бокьараб<pron><obl><genII>:бокьараблила
бокьараб<pron><obl><ins>:бокьараблид
бокьараб<pron><obl><sup><ess>:бокьарабликьа
бокьараб<pron><obl><erg>:бокьарабли
бокьараб<pron><abs>:бокьараб
боцдийо<adj><abs.sg>:боцдийо
боцдийо<adj><obl.sg>:боцдийа
боцдийо<adj><obl.pl>:боцдийā
боцдийо<adj><abs.pl>:боцдийā
боцдийо<adj><obl.sg>:боцдийа
боцдийо<adj><obl.sg>:боцдия
белӏна<num><compord><abs>:белӏнаийāлӏейо
белӏна<num><compord><abs>:белӏнаийāлIейо
белӏна<num><compord><abs>:белӏнаийāл1ейо
белӏна<num><hundred>:белӏначӏитӏ
белӏна<num><hundred>:белӏначӏитI
белӏна<num><hundred>:белӏначӏит1
белӏна<num><hundred>:белӏначIитӏ
белӏна<num><hundred>:белӏначIитI
белӏна<num><hundred>:белӏначIит1
белӏна<num><hundred>:белӏнач1итӏ
белӏна<num><hundred>:белӏнач1итI
белӏна<num><hundred>:белӏнач1ит1
белӏна<num><part>:белӏнана
белӏна<num><ord>:белӏнас
белӏна<num><ten>:белӏнайиг
белӏна<num><mult><part>:белӏейахна
белӏна<num><mult><part>:белӏейахна
белӏна<num><mult><part>:белӏеяхна
белӏна<num><compord><abs>:белIнаийāлӏейо
белӏна<num><compord><abs>:белIнаийāлIейо
белӏна<num><compord><abs>:белIнаийāл1ейо
белӏна<num><hundred>:белIначӏитӏ
белӏна<num><hundred>:белIначӏитI
белӏна<num><hundred>:белIначӏит1
белӏна<num><hundred>:белIначIитӏ
белӏна<num><hundred>:белIначIитI
белӏна<num><hundred>:белIначIит1
белӏна<num><hundred>:белIнач1итӏ
белӏна<num><hundred>:белIнач1итI
белӏна<num><hundred>:белIнач1ит1
белӏна<num><part>:белIнана
белӏна<num><ord>:белIнас
белӏна<num><ten>:белIнайиг
белӏна<num><mult><part>:белIейахна
белӏна<num><mult><part>:белIейахна
белӏна<num><mult><part>:белIеяхна
белӏна<num><compord><abs>:бел1наийāлӏейо
белӏна<num><compord><abs>:бел1наийāлIейо
белӏна<num><compord><abs>:бел1наийāл1ейо
белӏна<num><hundred>:бел1начӏитӏ
белӏна<num><hundred>:бел1начӏитI
белӏна<num><hundred>:бел1начӏит1
белӏна<num><hundred>:бел1начIитӏ
белӏна<num><hundred>:бел1начIитI
белӏна<num><hundred>:бел1начIит1
белӏна<num><hundred>:бел1нач1итӏ
белӏна<num><hundred>:бел1нач1итI
белӏна<num><hundred>:бел1нач1ит1
белӏна<num><part>:бел1нана
белӏна<num><ord>:бел1нас
белӏна<num><ten>:бел1найиг
белӏна<num><mult><part>:бел1ейахна
белӏна<num><mult><part>:бел1ейахна
белӏна<num><mult><part>:бел1еяхна
цихайо<adj><abs.sg>:цихайо
цихайо<adj><obl.sg>:цихайа
цихайо<adj><obl.sg>:цихайа
цихайо<adj><obl.sg>:цихая
до<pron><obl><genII>:диела
до<pron><obl><genI>:дие
до<pron><obl><dat>:дил
до<pron><abs>:до
до<pron><erg>:до
до<pron><obl><genII><sup><ess><abl>:дӣлакьас
до<pron><obl><ins>:дӣд
до<pron><obl><sup><ess>:дӣкьа
до<pron><obl><sup><ess><genII><abl>:дӣкьалас
до<pron><obl><sup><ess><dir><transl>:дӣкьадāкьā
до<pron><obl><sup><ess><transl>:дӣкьалкьā
до<pron><obl><sup><ess><abl>:дӣкьас
до<pron><obl><sup><ess><lat>:дӣкьал
до<pron><obl><sub><ess><abl>:дӣлӏсо
до<pron><obl><sub><ess><abl>:дӣлIсо
до<pron><obl><sub><ess><abl>:дӣл1со
сийо<pron><obl><dat>:лъинил
сийо<pron><obl><dat><neg>:лъинилна
сийо<pron><obl><dat><indf>:лъинилди
сийо<pron><obl><genI>:лъинис
сийо<pron><obl><genI><neg>:лъинисна
сийо<pron><obl><genI><indf>:лъинисди
сийо<pron><obl><genII>:лъинила
сийо<pron><obl><genII><neg>:лъинилана
сийо<pron><obl><genII><indf>:лъинилади
сийо<pron><obl><ins>:лъинид
сийо<pron><obl><ins><neg>:лъинидна
сийо<pron><obl><ins><indf>:лъинидди
сийо<pron><obl><sub><ess><neg>:лъинилӏна
сийо<pron><obl><sub><ess><indf>:лъинилӏди
сийо<pron><obl><sub><ess><neg>:лъинилIна
сийо<pron><obl><sub><ess><indf>:лъинилIди
сийо<pron><obl><sub><ess><neg>:лъинил1на
сийо<pron><obl><sub><ess><indf>:лъинил1ди
сийо<pron><obl><cont><ess><neg>:лъинилъна
сийо<pron><obl><cont><ess><indf>:лъинилъди
сийо<pron><obl><in><ess><neg>:лъиниъна
сийо<pron><obl><in><ess><indf>:лъиниъди
сийо<pron><obl><erg>:лъини
сийо<pron><obl><erg><neg>:лъинина
сийо<pron><obl><erg><indf>:лъиниди
сийо<pron><obl><sup><ess><neg>:лъинкьана
сийо<pron><obl><sup><ess><indf>:лъинкьади
сийо<pron><obl><ad><ess><neg>:лъингъана
сийо<pron><obl><ad><ess><indf>:лъингъади
сийо<pron><obl><apud><ess><neg>:лъиндойна
сийо<pron><obl><apud><ess><indf>:лъиндойди
сийо<pron><obl><cum><ess><neg>:лъингъойна
сийо<pron><obl><cum><ess><indf>:лъингъойди
сийо<pron><obl><poss><ess><neg>:лъинхъана
сийо<pron><obl><poss><ess><indf>:лъинхъади
сукӏо<pron><obl><genI>:лъой
сукӏо<pron><obl><genI><indf>:лъойсди
сукӏо<pron><obl><genI><neg>:лъойна
сукӏо<pron><obl><erg>:лъо
сукӏо<pron><obl><erg><neg>:лъона
сукӏо<pron><obl><erg><indf>:лъоди
сукӏо<pron><obl><dat>:лъōл
сукӏо<pron><obl><dat><neg>:лъōлна
сукӏо<pron><obl><dat><indf>:лъōлди
сукӏо<pron><obl><genII>:лъōла
сукӏо<pron><obl><genII><neg>:лъōлана
сукӏо<pron><obl><genII><indf>:лъōлади
сукӏо<pron><obl><ins>:лъōд
сукӏо<pron><obl><ins><neg>:лъōдна
сукӏо<pron><obl><ins><indf>:лъōдди
сукӏо<pron><obl><sup><ess><neg>:лъōкьана
сукӏо<pron><obl><sup><ess><indf>:лъōкьади
сукӏо<pron><obl><ad><ess><neg>:лъōгъана
сукӏо<pron><obl><ad><ess><indf>:лъōгъади
сукӏо<pron><obl><apud><ess><neg>:лъōдойна
сукӏо<pron><obl><apud><ess><indf>:лъōдойди
сукӏо<pron><obl><cum><ess><neg>:лъōгъойна
сукӏо<pron><obl><cum><ess><indf>:лъōгъойди
сукӏо<pron><obl><sub><ess><neg>:лъōлӏна
сукӏо<pron><obl><sub><ess><indf>:лъōлӏди
сукӏо<pron><obl><sub><ess><neg>:лъōлIна
сукӏо<pron><obl><sub><ess><indf>:лъōлIди
сукӏо<pron><obl><sub><ess><neg>:лъōл1на
сукӏо<pron><obl><sub><ess><indf>:лъōл1ди
сукӏо<pron><obl><cont><ess><neg>:лъōлъна
сукӏо<pron><obl><cont><ess><lat>:лъōлъил
сукӏо<pron><obl><cont><ess><indf>:лъōлъди
сукӏо<pron><obl><cont><ess><abl>:лъōлъсо
сукӏо<pron><obl><in><ess><neg>:лъōъна
сукӏо<pron><obl><in><ess><abl>:лъōъос
сукӏо<pron><obl><in><ess><lat>:лъōъол
сукӏо<pron><obl><in><ess><indf>:лъōъди
сукӏо<pron><obl><poss><ess><neg>:лъōхъана
сукӏо<pron><obl><poss><ess><indf>:лъōхъади
сийо<pron><abs>:сийо
сийо<pron><abs><neg>:сийона
сийо<pron><abs><neg><univ>:сийоназу
сийо<pron><abs><indf>:сийоди
сукӏо<pron><abs>:сукӏо
сукӏо<pron><abs><neg>:сукӏона
сукӏо<pron><abs><neg><univ>:сукӏоназу
сукӏо<pron><abs><indf>:сукӏоди
сукӏо<pron><abs>:сукIо
сукӏо<pron><abs><neg>:сукIона
сукӏо<pron><abs><neg><univ>:сукIоназу
сукӏо<pron><abs><indf>:сукIоди
сукӏо<pron><abs>:сук1о
сукӏо<pron><abs><neg>:сук1она
сукӏо<pron><abs><neg><univ>:сук1оназу
сукӏо<pron><abs><indf>:сук1оди
ми<pron><obl><genII>:дибола
ми<pron><obl><genI>:дибо
ми<pron><obl><dat>:дул
миже<pron><abs>:миже
миже<pron><erg>:миже
миже<pron><obl><dat>:мизол
миже<pron><obl><genI>:мизос
миже<pron><obl><genII>:мизола
миже<pron><obl><ins>:мизод
ми<pron><abs>:ми
ми<pron><erg>:ми
муьш<n><pl><abs>:муьшаь
жуь<refl><pl><obl><dat>:гьидел
жуь<refl><pl><obl><genI>:гьидеш
жуь<refl><pl><obl><genII>:гьидела
жуь<refl><pl><obl><ins>:гьидед
жуь<refl><pl><obl><sup><ess>:гьидекьа
жуь<refl><pl><obl><ad><ess>:гьидегъа
жуь<refl><pl><obl><apud><ess>:гьидедой
жуь<refl><pl><obl><cum><ess>:гьидегъой
жуь<refl><pl><obl><sub><ess>:гьиделӏ
жуь<refl><pl><obl><sub><ess>:гьиделI
жуь<refl><pl><obl><sub><ess>:гьидел1
жуь<refl><pl><obl><cont><ess>:гьиделъ
жуь<refl><pl><obl><in><ess>:гьидеъ
жуь<refl><pl><obl><poss><ess>:гьидехъа
жуь<refl><pl><obl><erg>:гьиде
жуь<refl><obl><dat>:гьинил
жуь<refl><obl><genI>:гьинис
жуь<refl><obl><genII>:гьинила
жуь<refl><obl><ins>:гьинид
жуь<refl><obl><sub><ess>:гьинилӏ
жуь<refl><obl><sub><ess>:гьинилI
жуь<refl><obl><sub><ess>:гьинил1
жуь<refl><obl><cont><ess>:гьинилъ
жуь<refl><obl><in><ess>:гьиниъ
жуь<refl><obl><erg>:гьини
жуь<refl><obl><sup><ess>:гьинкьа
жуь<refl><obl><ad><ess>:гьингъа
жуь<refl><obl><apud><ess>:гьиндой
жуь<refl><obl><cum><ess>:гьингъой
жуь<refl><obl><poss><ess>:гьинхъа
жес<adj><abs.pl>:жеса
жес<adj><abs.pl>:жесвā
жес<adj><abs.pl>:жесā
зогъ<v><inf>:зогъал
зогъ<v><neg><pst>:зогъйъеш
зогъ<v><neg><pfv.cvb>:зогъйчӏе
зогъ<v><neg><pfv.cvb>:зогъйчIе
зогъ<v><neg><pfv.cvb>:зогъйч1е
зогъ<v><neg><pst>:зогъеъеш
зогъ<v><neg><pfv.cvb>:зогъечӏе
зогъ<v><neg><pfv.cvb>:зогъечIе
зогъ<v><neg><pfv.cvb>:зогъеч1е
зогъ<v><pst>:зогъийо
зогъ<v><pst>:зогъло
зогъ<v><pfv.cvb>:зогъна
зогъ<v><imp>:зогъ
зогъ<v><prs>:зогъца
хъона<num><mult><part>:хъовахна
хъона<num><ord>:хъонас
хъуссо<adj><abs.sg>:хъуссо
хъуссо<adj><obl.sg>:хъусса
хъуссо<adj><obl.pl>:хъуссā
хъуссо<adj><abs.pl>:хъуссā
<I>атӏийо<pron><obl><dat>:атӏийал
<I>атӏийо<pron><obl><genI>:атӏийас
<I>атӏийо<pron><obl><genII>:атӏийала
<I>атӏийо<pron><obl><ins>:атӏийад
<I>атӏийо<pron><obl><sup><ess>:атӏийакьа
<I>атӏийо<pron><obl><erg>:атӏийа
<I>атӏийо<pron><abs>:атӏийо
<I>атӏийо<pron><obl><dat>:атӏийал
<I>атӏийо<pron><obl><genI>:атӏийас
<I>атӏийо<pron><obl><genII>:атӏийала
<I>атӏийо<pron><obl><ins>:атӏийад
<I>атӏийо<pron><obl><sup><ess>:атӏийакьа
<I>атӏийо<pron><obl><erg>:атӏийа
<I>атӏийо<pron><obl><dat>:атӏиял
<I>атӏийо<pron><obl><genI>:атӏияс
<I>атӏийо<pron><obl><genII>:атӏияла
<I>атӏийо<pron><obl><ins>:атӏияд
<I>атӏийо<pron><obl><sup><ess>:атӏиякьа
<I>атӏийо<pron><obl><erg>:атӏия
<I>атӏийо<pron><obl><dat>:атIийал
<I>атӏийо<pron><obl><genI>:атIийас
<I>атӏийо<pron><obl><genII>:атIийала
<I>атӏийо<pron><obl><ins>:атIийад
<I>атӏийо<pron><obl><sup><ess>:атIийакьа
<I>атӏийо<pron><obl><erg>:атIийа
<I>атӏийо<pron><abs>:атIийо
<I>атӏийо<pron><obl><dat>:атIийал
<I>атӏийо<pron><obl><genI>:атIийас
<I>атӏийо<pron><obl><genII>:атIийала
<I>атӏийо<pron><obl><ins>:атIийад
<I>атӏийо<pron><obl><sup><ess>:атIийакьа
<I>атӏийо<pron><obl><erg>:атIийа
<I>атӏийо<pron><obl><dat>:атIиял
<I>атӏийо<pron><obl><genI>:атIияс
<I>атӏийо<pron><obl><genII>:атIияла
<I>атӏийо<pron><obl><ins>:атIияд
<I>атӏийо<pron><obl><sup><ess>:атIиякьа
<I>атӏийо<pron><obl><erg>:атIия
<I>атӏийо<pron><obl><dat>:ат1ийал
<I>атӏийо<pron><obl><genI>:ат1ийас
<I>атӏийо<pron><obl><genII>:ат1ийала
<I>атӏийо<pron><obl><ins>:ат1ийад
<I>атӏийо<pron><obl><sup><ess>:ат1ийакьа
<I>атӏийо<pron><obl><erg>:ат1ийа
<I>атӏийо<pron><abs>:ат1ийо
<I>атӏийо<pron><obl><dat>:ат1ийал
<I>атӏийо<pron><obl><genI>:ат1ийас
<I>атӏийо<pron><obl><genII>:ат1ийала
<I>атӏийо<pron><obl><ins>:ат1ийад
<I>атӏийо<pron><obl><sup><ess>:ат1ийакьа
<I>атӏийо<pron><obl><erg>:ат1ийа
<I>атӏийо<pron><obl><dat>:ат1иял
<I>атӏийо<pron><obl><genI>:ат1ияс
<I>атӏийо<pron><obl><genII>:ат1ияла
<I>атӏийо<pron><obl><ins>:ат1ияд
<I>атӏийо<pron><obl><sup><ess>:ат1иякьа
<I>атӏийо<pron><obl><erg>:ат1ия
