<I>атӏийо<pron><obl><dat>:атӏийал
<I>атӏийо<pron><obl><erg>:атӏийа
<I>атӏийо<pron><obl><genI>:атӏийас
<I>атӏийо<pron><obl><genII>:атӏийала
<I>атӏийо<pron><obl><ins>:атӏийад
<I>атӏийо<pron><obl><super><essive>:атӏийакьа
<I>атӏийо<pron><abs>:атӏийо
алӏна<num><mult><part>:алӏовахна
алӏна<num><compord><abs>:алӏнаийāлӏейо
алӏна<num><hundred>:алӏначӏитӏ
алӏна<num><part>:алӏнана
алӏна<num><ord>:алӏнас
алӏна<num><ten>:алӏнайиг
акӏойо<adj><abs.pl>:акӏоа
акӏойо<adj><abs.pl>:акӏовā
абоц<n><pl><abs>:абоца
ацӏона<num><mult><part>:ацӏовахна
ацӏона<num><compord><abs>:ацӏонаийāлӏейо
ацӏона<num><part>:ацӏонана
ацӏона<num><ord>:ацӏонас
аваданаб<adj><obl.sg>:аваданабли
аваданаб<adj><obl.pl>:аваданабла
аслийаб<adj><abs.pl>:аслийабла
аькаьлаьб<adj><abs.pl>:аькаьлаьблаь
аьчӏена<num><mult><part>:аьчӏейахна
аьчӏена<num><compord><abs>:аьчӏенаийāлӏейо
аьчӏена<num><hundred>:аьчӏеначӏитӏ
аьчӏена<num><part>:аьчӏенана
аьчӏена<num><ord>:аьчӏенас
аьчӏена<num><ten>:аьчӏенайиг
тӏиган<n><pl><abs>:тӏигалла
илъна<num><compord><abs>:илънаийāлӏейо
илъна<num><compord><erg>:илънаийāлӏейа
илъна<num><compord><genI>:илънаийāлӏейас
илъна<num><hundred>:илъначӏитӏ
илъна<num><part>:илънана
илъна<num><ord>:илънас
илъна<num><ten>:илънайиг
илъна<num><ten><obl><dat>:илънайиглал
илъна<num><ten><obl><erg>:илънайигла
илъна<num><ten><obl><genI>:илънайиглас
илъна<num><ten><obl><genII>:илънайиглала
илъна<num><ten><obl><ins>:илънайиглад
илъна<num><mult><part>:илъейахна
иле<pron><obl><genII>:илла
иле<pron><obl><dat>:илол
иле<pron><obl><genI>:илос
иле<pron><obl><ins>:илод
иле<pron><abs>:иле
иле<pron><erg>:иле
ичӏей<n><pl><abs>:ичӏеййа
ичӏей<n><pl><abs>:ичӏейба
оьᴴкъоьнаь<num><mult><part>:оьᴴкъоьваьхна
оьᴴкъоьнаь<num><compord><abs>:оьᴴкъоьнаьийāлӏейо
оьᴴкъоьнаь<num><hundred>:оьᴴкъоьнаьчӏитӏ
оьᴴкъоьнаь<num><ord>:оьᴴкъоьнаьш
<II>атӏийо<pron><obl><dat>:йатӏийал
<II>атӏийо<pron><obl><erg>:йатӏийа
<II>атӏийо<pron><obl><genI>:йатӏийас
<II>атӏийо<pron><obl><genII>:йатӏийала
<II>атӏийо<pron><obl><ins>:йатӏийад
<II>атӏийо<pron><obl><super><essive>:йатӏийакьа
<II>атӏийо<pron><abs>:йатӏийо
<II>укъо<adj><abs.sg>:йукъо
<II>укъо<adj><obl.sg><dat>:йукъал
<II>укъо<adj><obl.sg><erg>:йукъа
<II>укъо<adj><obl.sg><genI>:йукъас
<II>укъо<adj><obl.sg><genII>:йукъала
<II>укъо<adj><obl.sg><ins>:йукъад
лӏаьммоь<adj><abs.sg><emp>:лӏаьммоьсо
лӏаьммоь<adj><abs.sg><emp>:лӏаьммоьшоь
лъана<num><mult><part>:лъахна
лъана<num><obl><dat>:лъанил
лъана<num><obl><erg>:лъани
лъана<num><obl><genI>:лъанис
лъана<num><obl><genII>:лъанила
лъана<num><obl><ins>:лъанид
лъана<num><abs>:лъана
лъана<num><compord><abs>:лъанаийāлӏейо
лъана<num><hundred>:лъаначӏитӏ
лъана<num><part>:лъанана
лъана<num><ord>:лъанас
лъана<num><ten>:лъанайиг
лъина<num><mult><part>:лъийахна
лъина<num><compord><abs>:лъинаийāлӏейо
лъина<num><hundred>:лъиначӏитӏ
лъина<num><hundred><obl><dat>:лъиначӏитӏлал
лъина<num><hundred><obl><erg>:лъиначӏитӏла
лъина<num><hundred><obl><genI>:лъиначӏитӏлас
лъина<num><hundred><obl><genII>:лъиначӏитӏлала
лъина<num><hundred><obl><ins>:лъиначӏитӏлад
лъина<num><part>:лъинана
лъина<num><ord>:лъинас
лъина<num><ord><obl><dat>:лъинаслил
лъина<num><ord><obl><erg>:лъинасли
лъина<num><ord><obl><genI>:лъинаслис
лъина<num><ord><obl><genII>:лъинаслила
лъина<num><ord><obl><ins>:лъинаслид
лъина<num><ten>:лъинайиг
гаьммоь<adj><abs.pl>:гаьммāь
гъаьгъаьтӏоь<adj><abs.sg>:гъаьгъаьтӏоь
гъаьгъаьтӏоь<adj><obl.sg>:гъаьгъаьтӏаь
гъаьгъаьтӏоь<adj><obl.pl>:гъаьгъаьтӏāь
гъаьгъаьтӏоь<adj><abs.pl>:гъаьгъаьтӏāь
гьасагъас<adj><abs.pl>:гьасагъаса
гьасагъас<adj><abs.pl>:гьасагъасвā
гьасагъас<adj><abs.pl>:гьасагъасā
гьоᴴс<num><mult>:гьаᴴкъкъа
гьо<dem><dist.2/3><abs>:гього
гьо<dem><med.2/3><abs>:гьоло
гьо<dem><prox.2/3><abs>:гьодо
гьо<dem><med.2/3><obl><dat>:гьоллъол
гьо<dem><med.2/3><obl><erg>:гьоллъо
гьо<dem><med.2/3><obl><genI>:гьоллъос
гьо<dem><med.2/3><obl><genII>:гьоллъола
гьо<dem><med.2/3><obl><ins>:гьоллъод
гьо<dem><med.2/3><pl><abs>:гьоллōл
гьо<dem><med.2/3><obl.pl><dat>:гьоллол
гьо<dem><med.2/3><obl.pl><erg>:гьолло
гьо<dem><med.2/3><obl.pl><genI>:гьоллос
гьо<dem><med.2/3><obl.pl><genII>:гьоллола
гьо<dem><med.2/3><obl.pl><ins>:гьоллод
гьо<dem><med.2/3><obl><dat>:гьолълъол
гьо<dem><med.2/3><obl><erg>:гьолълъо
гьо<dem><med.2/3><obl><genI>:гьолълъос
гьо<dem><med.2/3><obl><genII>:гьолълъола
гьо<dem><med.2/3><obl><ins>:гьолълъод
гьо<dem><prox.2/3><obl><dat>:гьолӏол
гьо<dem><prox.2/3><obl><erg>:гьолӏо
гьо<dem><prox.2/3><obl><genI>:гьолӏос
гьо<dem><prox.2/3><obl><genII>:гьолӏола
гьо<dem><prox.2/3><obl><ins>:гьолӏод
гьо<dem><dist.2/3><obl><dat>:гьоглӏол
гьо<dem><dist.2/3><obl><erg>:гьоглӏо
гьо<dem><dist.2/3><obl><genI>:гьоглӏос
гьо<dem><dist.2/3><obl><genII>:гьоглӏола
гьо<dem><dist.2/3><obl><ins>:гьоглӏод
гьо<dem><dist.2/3><obl.pl><dat>:гьоглол
гьо<dem><dist.2/3><obl.pl><erg>:гьогло
гьо<dem><dist.2/3><obl.pl><genI>:гьоглос
гьо<dem><dist.2/3><obl.pl><genII>:гьоглола
гьо<dem><dist.2/3><obl.pl><ins>:гьоглод
гьо<dem><dist.2/3><pl><abs>:гьоггōл
гьо<dem><prox.2/3><obl.pl><dat>:гьодлол
гьо<dem><prox.2/3><obl.pl><erg>:гьодло
гьо<dem><prox.2/3><obl.pl><genI>:гьодлос
гьо<dem><prox.2/3><obl.pl><genII>:гьодлола
гьо<dem><prox.2/3><obl.pl><ins>:гьодлод
гьо<dem><prox.2/3><pl><abs>:гьоддōл
гьоᴴс<num><abs>:гьоᴴс
гьоᴴс<num><compord><abs>:гьоᴴсийāлӏейо
гьоᴴс<num><hundred>:гьоᴴсчӏитӏ
гьоᴴс<num><hundred><inf><mult>:гьоᴴсчӏитӏйах
гьу<dem><med.1/4><obl><dat>:гьолцол
гьу<dem><med.1/4><obl><erg>:гьолцо
гьу<dem><med.1/4><obl><genI>:гьолцос
гьу<dem><med.1/4><obl><genII>:гьолцола
гьу<dem><med.1/4><obl><genII><cont><essive><lative>:гьолцолалъил
гьу<dem><med.1/4><obl><genII><in><essive><lative>:гьолцолаъал
гьу<dem><med.1/4><obl><ins>:гьолцод
гьу<dem><med.1/4><obl><super><essive><dir><translative>:гьолцокьадāкьā
гьу<dem><med.1/4><obl><super><essive><translative>:гьолцокьалкьā
гьу<dem><med.1/4><obl><cont><essive><genII><lative>:гьолцолълал
гьу<dem><med.1/4><obl><cont><essive><ablative>:гьолцолъсо
гьу<dem><med.1/4><obl><cont><essive><lative>:гьолцолъил
гьу<dem><med.1/4><obl><in><essive><ablative>:гьолцоъос
гьу<dem><med.1/4><obl><in><essive><lative>:гьолцоъол
гьу<dem><dist.1/4><obl><dat>:гьогцол
гьу<dem><dist.1/4><obl><erg>:гьогцо
гьу<dem><dist.1/4><obl><genI>:гьогцос
гьу<dem><dist.1/4><obl><genII>:гьогцола
гьу<dem><dist.1/4><obl><ins>:гьогцод
гьу<dem><prox.1/4><obl><dat>:гьоцол
гьу<dem><prox.1/4><obl><erg>:гьоцо
гьу<dem><prox.1/4><obl><genI>:гьоцос
гьу<dem><prox.1/4><obl><genII>:гьоцола
гьу<dem><prox.1/4><obl><ins>:гьоцод
гьу<dem><dist.1/4><abs>:гьуги
гьу<dem><med.1/4><abs>:гьули
гьу<dem><prox.1/4><abs>:гьуди
гьоᴴс<num><obl><dat>:сидил
гьоᴴс<num><obl><erg>:сиди
гьоᴴс<num><obl><genI>:сидис
гьоᴴс<num><obl><genII>:сидила
гьоᴴс<num><obl><ins>:сидид
гьоᴴс<num><obl><sub><essive>:сидилӏ
гьоᴴс<num><obl><sub><essive><genII>:сидилӏла
гьоᴴс<num><obl><sub><essive><genII><lative>:сидилӏлал
гьоᴴс<num><obl><sub><essive><genII><translative>:сидилӏлакьā
гьоᴴс<num><obl><sub><essive><ablative>:сидилӏсо
гьоᴴс<num><obl><sub><essive><dir>:сидилӏдā
гьоᴴс<num><obl><sub><essive><dir><ablative>:сидилӏдāс
гьоᴴс<num><obl><sub><essive><dir><lative>:сидилӏдāл
гьоᴴс<num><obl><sub><essive><dir><translative>:сидилӏдāкьā
гьоᴴс<num><obl><sub><essive><lative>:сидилӏил
гьоᴴс<num><obl><sub><essive><translative>:сидилӏкьā
гьоᴴс<num><obl><cont><essive>:сидилъ
гьоᴴс<num><obl><cont><essive><ablative>:сидилъсо
гьоᴴс<num><obl><cont><essive><dir>:сидилъдā
гьоᴴс<num><obl><cont><essive><dir><ablative>:сидилъдāс
гьоᴴс<num><obl><cont><essive><dir><lative>:сидилъдāл
гьоᴴс<num><obl><cont><essive><dir><translative>:сидилъдāкьā
гьоᴴс<num><obl><cont><essive><lative>:сидилъил
гьоᴴс<num><obl><cont><essive><translative>:сидилъкьā
гьоᴴс<num><obl><in><essive>:сидиъ
гьоᴴс<num><obl><in><essive><ablative>:сидиъис
гьоᴴс<num><obl><in><essive><dir>:сидиъдā
гьоᴴс<num><obl><in><essive><dir><ablative>:сидиъдāс
гьоᴴс<num><obl><in><essive><dir><lative>:сидиъдāл
гьоᴴс<num><obl><in><essive><dir><translative>:сидиъдāкьā
гьоᴴс<num><obl><in><essive><lative>:сидиъил
гьоᴴс<num><obl><in><essive><translative>:сидиъкьā
гьоᴴс<num><genII><super><essive>:сидлакьа
гьоᴴс<num><genII><super><essive><ablative>:сидлакьас
гьоᴴс<num><genII><super><essive><lative>:сидлакьал
гьоᴴс<num><genII><ad><essive>:сидлагъа
гьоᴴс<num><genII><ad><essive><ablative>:сидлагъас
гьоᴴс<num><genII><ad><essive><lative>:сидлагъал
гьоᴴс<num><genII><sub><essive>:сидлалӏ
гьоᴴс<num><genII><sub><essive><lative>:сидлалӏил
гьоᴴс<num><super><essive>:сидкьа
гьоᴴс<num><super><essive><genII>:сидкьала
гьоᴴс<num><super><essive><genII><ablative>:сидкьалас
гьоᴴс<num><super><essive><genII><lative>:сидкьалал
гьоᴴс<num><super><essive><genII><translative>:сидкьалакьā
гьоᴴс<num><super><essive><ablative>:сидкьас
гьоᴴс<num><super><essive><dir>:сидкьадā
гьоᴴс<num><super><essive><dir><ablative>:сидкьадāс
гьоᴴс<num><super><essive><dir><lative>:сидкьадāл
гьоᴴс<num><super><essive><dir><translative>:сидкьадāкьā
гьоᴴс<num><super><essive><lative>:сидкьал
гьоᴴс<num><super><essive><translative>:сидкьалкьā
гьоᴴс<num><ad><essive>:сидгъа
гьоᴴс<num><ad><essive><genII><ablative>:сидгъалас
гьоᴴс<num><ad><essive><genII><lative>:сидгъалал
гьоᴴс<num><ad><essive><genII><translative>:сидгъалакьā
гьоᴴс<num><ad><essive><ablative>:сидгъас
гьоᴴс<num><ad><essive><dir>:сидгъадā
гьоᴴс<num><ad><essive><dir><ablative>:сидгъадāс
гьоᴴс<num><ad><essive><dir><lative>:сидгъадāл
гьоᴴс<num><ad><essive><dir><translative>:сидгъадāкьā
гьоᴴс<num><ad><essive><lative>:сидгъал
гьоᴴс<num><ad><essive><translative>:сидгъалкьā
гьоᴴс<num><apud><essive>:сиддой
гьоᴴс<num><apud><essive><ablative>:сиддойс
гьоᴴс<num><apud><essive><dir>:сиддойдā
гьоᴴс<num><apud><essive><dir><ablative>:сиддойдāс
гьоᴴс<num><apud><essive><dir><lative>:сиддойдāл
гьоᴴс<num><apud><essive><dir><translative>:сиддойдāкьā
гьоᴴс<num><apud><essive><lative>:сиддойл
гьоᴴс<num><apud><essive><translative>:сиддойкьā
гьоᴴс<num><cum><essive>:сидгъой
гьоᴴс<num><cum><essive><ablative>:сидгъойс
гьоᴴс<num><cum><essive><dir>:сидгъойдā
гьоᴴс<num><cum><essive><dir><ablative>:сидгъойдāс
гьоᴴс<num><cum><essive><dir><lative>:сидгъойдāл
гьоᴴс<num><cum><essive><dir><translative>:сидгъойдāкьā
гьоᴴс<num><cum><essive><lative>:сидгъойл
гьоᴴс<num><cum><essive><translative>:сидгъойкьā
гьоᴴс<num><poss><essive>:сидхъа
гьоᴴс<num><poss><essive><ablative>:сидхъас
гьоᴴс<num><poss><essive><dir>:сидхъадā
гьоᴴс<num><poss><essive><dir><ablative>:сидхъадāс
гьоᴴс<num><poss><essive><dir><lative>:сидхъадāл
гьоᴴс<num><poss><essive><dir><translative>:сидхъадāкьā
гьоᴴс<num><poss><essive><lative>:сидхъал
гьоᴴс<num><poss><essive><translative>:сидхъалкьā
кид<n><obl><genII>:киббала
къона<num><mult><part>:кӏахна
къаькъаьлоь<adj><abs.pl>:къаькъаьлāь
къона<num><compord><abs>:къонаийāлӏейо
къона<num><hundred>:къоначӏитӏ
къона<num><part>:къонана
къона<num><ord>:къонас
<III>атӏийо<pron><obl><dat>:батӏийал
<III>атӏийо<pron><obl><erg>:батӏийа
<III>атӏийо<pron><obl><genI>:батӏийас
<III>атӏийо<pron><obl><genII>:батӏийала
<III>атӏийо<pron><obl><ins>:батӏийад
<III>атӏийо<pron><obl><super><essive>:батӏийакьа
<III>атӏийо<pron><abs>:батӏийо
<refl>:жуь
<refl><pl>:жуьвōьл
<refl>:зу
<refl><pl>:зувōьл
<thousand><obl><dat>:гьазайлал
<thousand><obl><erg>:гьазайла
<thousand><obl><genI>:гьазайлас
<thousand><obl><genII>:гьазайлала
<thousand><obl><ins>:гьазайлад
бикдийо<adj><abs.pl>:бикдийā
бокьараб<pron><abs>:бокьараб
бокьараб<pron><obl><dat>:бокьараблил
бокьараб<pron><obl><erg>:бокьарабли
бокьараб<pron><obl><genI>:бокьараблис
бокьараб<pron><obl><genII>:бокьараблила
бокьараб<pron><obl><ins>:бокьараблид
бокьараб<pron><obl><super><essive>:бокьарабликьа
боцдийо<adj><abs.sg>:боцдийо
боцдийо<adj><obl.sg>:боцдийа
боцдийо<adj><obl.pl>:боцдийā
боцдийо<adj><abs.pl>:боцдийā
белӏна<num><compord><abs>:белӏнаийāлӏейо
белӏна<num><hundred>:белӏначӏитӏ
белӏна<num><part>:белӏнана
белӏна<num><ord>:белӏнас
белӏна<num><ten>:белӏнайиг
белӏна<num><mult><part>:белӏейахна
цихайо<adj><abs.sg>:цихайо
цихайо<adj><obl.sg>:цихайа
до<pron><obl><dat>:дил
до<pron><obl><genI>:дие
до<pron><obl><genII>:диела
до<pron><abs>:до
до<pron><erg>:до
до<pron><obl><genII><super><essive><ablative>:дӣлакьас
до<pron><obl><ins>:дӣд
до<pron><obl><super><essive>:дӣкьа
до<pron><obl><super><essive><genII><ablative>:дӣкьалас
до<pron><obl><super><essive><ablative>:дӣкьас
до<pron><obl><super><essive><dir><translative>:дӣкьадāкьā
до<pron><obl><super><essive><lative>:дӣкьал
до<pron><obl><super><essive><translative>:дӣкьалкьā
до<pron><obl><sub><essive><ablative>:дӣлӏсо
сийо<pron><obl><super><essive><neg>:лъинкьана
сийо<pron><obl><super><essive><indf>:лъинкьади
сийо<pron><obl><ad><essive><neg>:лъингъана
сийо<pron><obl><ad><essive><indf>:лъингъади
сийо<pron><obl><apud><essive><neg>:лъиндойна
сийо<pron><obl><apud><essive><indf>:лъиндойди
сийо<pron><obl><cum><essive><neg>:лъингъойна
сийо<pron><obl><cum><essive><indf>:лъингъойди
сийо<pron><obl><poss><essive><neg>:лъинхъана
сийо<pron><obl><poss><essive><indf>:лъинхъади
сийо<pron><obl><dat>:лъинил
сийо<pron><obl><dat><neg>:лъинилна
сийо<pron><obl><dat><indf>:лъинилди
сийо<pron><obl><erg>:лъини
сийо<pron><obl><erg><neg>:лъинина
сийо<pron><obl><erg><indf>:лъиниди
сийо<pron><obl><genI>:лъинис
сийо<pron><obl><genI><neg>:лъинисна
сийо<pron><obl><genI><indf>:лъинисди
сийо<pron><obl><genII>:лъинила
сийо<pron><obl><genII><neg>:лъинилана
сийо<pron><obl><genII><indf>:лъинилади
сийо<pron><obl><ins>:лъинид
сийо<pron><obl><ins><neg>:лъинидна
сийо<pron><obl><ins><indf>:лъинидди
сийо<pron><obl><sub><essive><neg>:лъинилӏна
сийо<pron><obl><sub><essive><indf>:лъинилӏди
сийо<pron><obl><cont><essive><neg>:лъинилъна
сийо<pron><obl><cont><essive><indf>:лъинилъди
сийо<pron><obl><in><essive><neg>:лъиниъна
сийо<pron><obl><in><essive><indf>:лъиниъди
сукӏо<pron><obl><erg>:лъо
сукӏо<pron><obl><erg><neg>:лъона
сукӏо<pron><obl><erg><indf>:лъоди
сукӏо<pron><obl><genI>:лъой
сукӏо<pron><obl><genI><indf>:лъойсди
сукӏо<pron><obl><genI><neg>:лъойна
сукӏо<pron><obl><dat>:лъōл
сукӏо<pron><obl><dat><neg>:лъōлна
сукӏо<pron><obl><dat><indf>:лъōлди
сукӏо<pron><obl><genII>:лъōла
сукӏо<pron><obl><genII><neg>:лъōлана
сукӏо<pron><obl><genII><indf>:лъōлади
сукӏо<pron><obl><ins>:лъōд
сукӏо<pron><obl><ins><neg>:лъōдна
сукӏо<pron><obl><ins><indf>:лъōдди
сукӏо<pron><obl><super><essive><neg>:лъōкьана
сукӏо<pron><obl><super><essive><indf>:лъōкьади
сукӏо<pron><obl><ad><essive><neg>:лъōгъана
сукӏо<pron><obl><ad><essive><indf>:лъōгъади
сукӏо<pron><obl><apud><essive><neg>:лъōдойна
сукӏо<pron><obl><apud><essive><indf>:лъōдойди
сукӏо<pron><obl><cum><essive><neg>:лъōгъойна
сукӏо<pron><obl><cum><essive><indf>:лъōгъойди
сукӏо<pron><obl><sub><essive><neg>:лъōлӏна
сукӏо<pron><obl><sub><essive><indf>:лъōлӏди
сукӏо<pron><obl><cont><essive><neg>:лъōлъна
сукӏо<pron><obl><cont><essive><ablative>:лъōлъсо
сукӏо<pron><obl><cont><essive><lative>:лъōлъил
сукӏо<pron><obl><cont><essive><indf>:лъōлъди
сукӏо<pron><obl><in><essive><neg>:лъōъна
сукӏо<pron><obl><in><essive><ablative>:лъōъос
сукӏо<pron><obl><in><essive><lative>:лъōъол
сукӏо<pron><obl><in><essive><indf>:лъōъди
сукӏо<pron><obl><poss><essive><neg>:лъōхъана
сукӏо<pron><obl><poss><essive><indf>:лъōхъади
сийо<pron><abs>:сийо
сийо<pron><abs><neg>:сийона
сийо<pron><abs><neg><univ>:сийоназу
сийо<pron><abs><indf>:сийоди
сукӏо<pron><abs>:сукӏо
сукӏо<pron><abs><neg>:сукӏона
сукӏо<pron><abs><neg><univ>:сукӏоназу
сукӏо<pron><abs><indf>:сукӏоди
ми<pron><obl><genI>:дибо
ми<pron><obl><genII>:дибола
ми<pron><obl><dat>:дул
ми<pron><obl><ins>:дӯд
ми<pron><abs>:ми
ми<pron><erg>:ми
миже<pron><abs>:миже
миже<pron><erg>:миже
миже<pron><obl><dat>:мизол
миже<pron><obl><genI>:мизос
миже<pron><obl><genII>:мизола
миже<pron><obl><ins>:мизод
муьш<n><pl><abs>:муьшаь
жуь<refl><pl><obl><dat>:гьидел
жуь<refl><pl><obl><erg>:гьиде
жуь<refl><pl><obl><genI>:гьидеш
жуь<refl><pl><obl><genII>:гьидела
жуь<refl><pl><obl><ins>:гьидед
жуь<refl><pl><obl><super><essive>:гьидекьа
жуь<refl><pl><obl><ad><essive>:гьидегъа
жуь<refl><pl><obl><apud><essive>:гьидедой
жуь<refl><pl><obl><cum><essive>:гьидегъой
жуь<refl><pl><obl><sub><essive>:гьиделӏ
жуь<refl><pl><obl><cont><essive>:гьиделъ
жуь<refl><pl><obl><in><essive>:гьидеъ
жуь<refl><pl><obl><poss><essive>:гьидехъа
жуь<refl><obl><super><essive>:гьинкьа
жуь<refl><obl><ad><essive>:гьингъа
жуь<refl><obl><apud><essive>:гьиндой
жуь<refl><obl><cum><essive>:гьингъой
жуь<refl><obl><poss><essive>:гьинхъа
жуь<refl><obl><dat>:гьинил
жуь<refl><obl><erg>:гьини
жуь<refl><obl><genI>:гьинис
жуь<refl><obl><genII>:гьинила
жуь<refl><obl><ins>:гьинид
жуь<refl><obl><sub><essive>:гьинилӏ
жуь<refl><obl><cont><essive>:гьинилъ
жуь<refl><obl><in><essive>:гьиниъ
жес<adj><abs.pl>:жеса
жес<adj><abs.pl>:жесвā
жес<adj><abs.pl>:жесā
хъона<num><mult><part>:хъовахна
хъона<num><ord>:хъонас
хъуссо<adj><abs.sg>:хъуссо
хъуссо<adj><obl.sg>:хъусса
хъуссо<adj><obl.pl>:хъуссā
хъуссо<adj><abs.pl>:хъуссā
