<cl>атӏийо<obl><dat>:атӏийал
<cl>атӏийо<obl><erg>:атӏийа
<cl>атӏийо<obl><genI>:атӏийас
<cl>атӏийо<obl><genII>:атӏийала
<cl>атӏийо<obl><ins>:атӏийад
<cl>атӏийо<obl><super><essive>:атӏийакьа
<cl>атӏийо<abs>:атӏийо
<cl>атӏийо<obl><dat>:йатӏийал
<cl>атӏийо<obl><erg>:йатӏийа
<cl>атӏийо<obl><genI>:йатӏийас
<cl>атӏийо<obl><genII>:йатӏийала
<cl>атӏийо<obl><ins>:йатӏийад
<cl>атӏийо<obl><super><essive>:йатӏийакьа
<cl>атӏийо<abs>:йатӏийо
<cl>атӏийо<obl><dat>:батӏийал
<cl>атӏийо<obl><erg>:батӏийа
<cl>атӏийо<obl><genI>:батӏийас
<cl>атӏийо<obl><genII>:батӏийала
<cl>атӏийо<obl><ins>:батӏийад
<cl>атӏийо<obl><super><essive>:батӏийакьа
<cl>атӏийо<abs>:батӏийо
алӏна<mult><part>:алӏовахна
алӏна<compord><abs>:алӏнаийāлӏейо
алӏна<hundred>:алӏначӏитӏ
алӏна<part>:алӏнана
алӏна<ord>:алӏнас
алӏна<ten>:алӏнайиг
ацӏона<compord><abs>:ацӏонаийāлӏейо
ацӏона<part>:ацӏонана
ацӏона<ord>:ацӏонас
ацӏона<mult><part>:ацӏовахна
аьчӏена<mult><part>:аьчӏейахна
аьчӏена<compord><abs>:аьчӏенаийāлӏейо
аьчӏена<hundred>:аьчӏеначӏитӏ
аьчӏена<part>:аьчӏенана
аьчӏена<ord>:аьчӏенас
аьчӏена<ten>:аьчӏенайиг
иле<obl><genII>:илла
иле<obl><dat>:илол
иле<obl><genI>:илос
иле<obl><ins>:илод
иле<abs>:иле
иле<erg>:иле
илъна<compord><abs>:илънаийāлӏейо
илъна<compord><erg>:илънаийāлӏейа
илъна<compord><genI>:илънаийāлӏейас
илъна<hundred>:илъначӏитӏ
илъна<part>:илънана
илъна<ord>:илънас
илъна<ten>:илънайиг
илъна<ten><obl><dat>:илънайиглал
илъна<ten><obl><erg>:илънайигла
илъна<ten><obl><genI>:илънайиглас
илъна<ten><obl><genII>:илънайиглала
илъна<ten><obl><ins>:илънайиглад
илъна<mult><part>:илъейахна
оьᴴкъоьнаь<compord><abs>:оьᴴкъоьнаьийāлӏейо
оьᴴкъоьнаь<hundred>:оьᴴкъоьнаьчӏитӏ
оьᴴкъоьнаь<part>:оьᴴкъоьнаьна
оьᴴкъоьнаь<ord>:оьᴴкъоьнаьш
оьᴴкъоьнаь<ten>:оьᴴкъоьнаьйиг
оьᴴкъоьнаь<mult><part>:оьᴴкъоьваьхна
<refl>:зу
<refl><pl>:зуво̄ьл
<refl>:жуь
<refl><pl>:жуьво̄ьл
лъана<mult><part>:лъахна
лъана<obl><dat>:лъанил
лъана<obl><erg>:лъани
лъана<obl><genI>:лъанис
лъана<obl><genII>:лъанила
лъана<obl><ins>:лъанид
лъана<abs>:лъана
лъана<compord><abs>:лъанаийāлӏейо
лъана<hundred>:лъаначӏитӏ
лъана<part>:лъанана
лъана<ord>:лъанас
лъана<ten>:лъанайиг
лъина<mult><part>:лъийахна
лъина<compord><abs>:лъинаийāлӏейо
лъина<hundred>:лъиначӏитӏ
лъина<hundred><obl><dat>:лъиначӏитӏлал
лъина<hundred><obl><erg>:лъиначӏитӏла
лъина<hundred><obl><genI>:лъиначӏитӏлас
лъина<hundred><obl><genII>:лъиначӏитӏлала
лъина<hundred><obl><ins>:лъиначӏитӏлад
лъина<part>:лъинана
лъина<ord>:лъинас
лъина<ord><obl><dat>:лъинаслил
лъина<ord><obl><erg>:лъинасли
лъина<ord><obl><genI>:лъинаслис
лъина<ord><obl><genII>:лъинаслила
лъина<ord><obl><ins>:лъинаслид
лъина<ten>:лъинайиг
бокьараб<abs>:бокьараб
бокьараб<obl><dat>:бокьараблил
бокьараб<obl><erg>:бокьарабли
бокьараб<obl><genI>:бокьараблис
бокьараб<obl><genII>:бокьараблила
бокьараб<obl><ins>:бокьараблид
бокьараб<obl><super><essive>:бокьарабликьа
белӏна<compord><abs>:белӏнаийāлӏейо
белӏна<hundred>:белӏначӏитӏ
белӏна<part>:белӏнана
белӏна<ord>:белӏнас
белӏна<ten>:белӏнайиг
белӏна<mult><part>:белӏейахна
къона<mult><part>:кӏахна
къона<compord><abs>:къонаийāлӏейо
къона<hundred>:къоначӏитӏ
къона<part>:къонана
къона<ord>:къонас
гьоᴴс<ord>:аьᴴйдда̄ьш
гьазай<thousand><obl><dat>:гьазайлал
гьазай<thousand><obl><erg>:гьазайла
гьазай<thousand><obl><genI>:гьазайлас
гьазай<thousand><obl><genII>:гьазайлала
гьазай<thousand><obl><ins>:гьазайлад
гьазай<thousand><part><ord>:гьазайнас
гьазай<thousand><inf><mult>:гьазаййах
гьоᴴс<mult>:гьаᴴкъкъа
гьо<dist.2/3><abs>:гього
гьо<dist.2/3><obl><dat>:гьоглӏол
гьо<dist.2/3><obl><erg>:гьоглӏо
гьо<dist.2/3><obl><genI>:гьоглӏос
гьо<dist.2/3><obl><genII>:гьоглӏола
гьо<dist.2/3><obl><ins>:гьоглӏод
гьо<dist.2/3><pl><abs>:гьогго̄л
гьо<dist.2/3><obl.pl><dat>:гьоглол
гьо<dist.2/3><obl.pl><erg>:гьогло
гьо<dist.2/3><obl.pl><genI>:гьоглос
гьо<dist.2/3><obl.pl><genII>:гьоглола
гьо<dist.2/3><obl.pl><ins>:гьоглод
гьо<med.2/3><abs>:гьоло
гьо<med.2/3><obl><dat>:гьоллъол
гьо<med.2/3><obl><erg>:гьоллъо
гьо<med.2/3><obl><genI>:гьоллъос
гьо<med.2/3><obl><genII>:гьоллъола
гьо<med.2/3><obl><ins>:гьоллъод
гьо<med.2/3><pl><abs>:гьолло̄л
гьо<med.2/3><obl.pl><dat>:гьоллол
гьо<med.2/3><obl.pl><erg>:гьолло
гьо<med.2/3><obl.pl><genI>:гьоллос
гьо<med.2/3><obl.pl><genII>:гьоллола
гьо<med.2/3><obl.pl><ins>:гьоллод
гьо<prox.2/3><obl><dat>:гьолӏол
гьо<prox.2/3><obl><erg>:гьолӏо
гьо<prox.2/3><obl><genI>:гьолӏос
гьо<prox.2/3><obl><genII>:гьолӏола
гьо<prox.2/3><obl><ins>:гьолӏод
гьо<prox.2/3><abs>:гьодо
гьо<prox.2/3><pl><abs>:гьоддо̄л
гьо<prox.2/3><obl.pl><dat>:гьодлол
гьо<prox.2/3><obl.pl><erg>:гьодло
гьо<prox.2/3><obl.pl><genI>:гьодлос
гьо<prox.2/3><obl.pl><genII>:гьодлола
гьо<prox.2/3><obl.pl><ins>:гьодлод
гьоᴴс<abs>:гьоᴴс
гьоᴴс<compord><abs>:гьоᴴсийāлӏейо
гьоᴴс<hundred>:гьоᴴсчӏитӏ
гьоᴴс<hundred><inf><mult>:гьоᴴсчӏитӏйах
гьу<dist.1/4><obl><dat>:гьогцол
гьу<dist.1/4><obl><erg>:гьогцо
гьу<dist.1/4><obl><genI>:гьогцос
гьу<dist.1/4><obl><genII>:гьогцола
гьу<dist.1/4><obl><ins>:гьогцод
гьу<med.1/4><obl><dat>:гьолцол
гьу<med.1/4><obl><erg>:гьолцо
гьу<med.1/4><obl><genI>:гьолцос
гьу<med.1/4><obl><genII>:гьолцола
гьу<med.1/4><obl><genII><cont><essive><lative>:гьолцолалъил
гьу<med.1/4><obl><genII><in><essive><lative>:гьолцолаъал
гьу<med.1/4><obl><ins>:гьолцод
гьу<med.1/4><obl><super><essive><dir><translative>:гьолцокьада̄кьа̄
гьу<med.1/4><obl><super><essive><translative>:гьолцокьалкьа̄
гьу<med.1/4><obl><cont><essive><genII><lative>:гьолцолълал
гьу<med.1/4><obl><cont><essive><ablative>:гьолцолъсо
гьу<med.1/4><obl><cont><essive><lative>:гьолцолъил
гьу<med.1/4><obl><in><essive><ablative>:гьолцоъос
гьу<med.1/4><obl><in><essive><lative>:гьолцоъол
гьу<prox.1/4><obl><dat>:гьоцол
гьу<prox.1/4><obl><erg>:гьоцо
гьу<prox.1/4><obl><genI>:гьоцос
гьу<prox.1/4><obl><genII>:гьоцола
гьу<prox.1/4><obl><ins>:гьоцод
гьу<dist.1/4><abs>:гьуги
гьу<med.1/4><abs>:гьули
гьу<prox.1/4><abs>:гьуди
гьоᴴс<obl><dat>:сидил
гьоᴴс<obl><erg>:сиди
гьоᴴс<obl><genI>:сидис
гьоᴴс<obl><genII>:сидила
гьоᴴс<obl><ins>:сидид
гьоᴴс<obl><sub><essive>:сидилӏ
гьоᴴс<obl><sub><essive><genII>:сидилӏла
гьоᴴс<obl><sub><essive><genII><lative>:сидилӏлал
гьоᴴс<obl><sub><essive><genII><translative>:сидилӏлакьа̄
гьоᴴс<obl><sub><essive><ablative>:сидилӏсо
гьоᴴс<obl><sub><essive><dir>:сидилӏда̄
гьоᴴс<obl><sub><essive><dir><ablative>:сидилӏда̄с
гьоᴴс<obl><sub><essive><dir><lative>:сидилӏда̄л
гьоᴴс<obl><sub><essive><dir><translative>:сидилӏда̄кьа̄
гьоᴴс<obl><sub><essive><lative>:сидилӏил
гьоᴴс<obl><sub><essive><translative>:сидилӏкьа̄
гьоᴴс<obl><cont><essive>:сидилъ
гьоᴴс<obl><cont><essive><ablative>:сидилъсо
гьоᴴс<obl><cont><essive><dir>:сидилъда̄
гьоᴴс<obl><cont><essive><dir><ablative>:сидилъда̄с
гьоᴴс<obl><cont><essive><dir><lative>:сидилъда̄л
гьоᴴс<obl><cont><essive><dir><translative>:сидилъда̄кьа̄
гьоᴴс<obl><cont><essive><lative>:сидилъил
гьоᴴс<obl><cont><essive><translative>:сидилъкьа̄
гьоᴴс<obl><in><essive>:сидиъ
гьоᴴс<obl><in><essive><ablative>:сидиъис
гьоᴴс<obl><in><essive><dir>:сидиъда̄
гьоᴴс<obl><in><essive><dir><ablative>:сидиъда̄с
гьоᴴс<obl><in><essive><dir><lative>:сидиъда̄л
гьоᴴс<obl><in><essive><dir><translative>:сидиъда̄кьа̄
гьоᴴс<obl><in><essive><lative>:сидиъил
гьоᴴс<obl><in><essive><translative>:сидиъкьа̄
гьоᴴс<genII><super><essive>:сидлакьа
гьоᴴс<genII><super><essive><ablative>:сидлакьас
гьоᴴс<genII><super><essive><lative>:сидлакьал
гьоᴴс<genII><ad><essive>:сидлагъа
гьоᴴс<genII><ad><essive><ablative>:сидлагъас
гьоᴴс<genII><ad><essive><lative>:сидлагъал
гьоᴴс<genII><sub><essive>:сидлалӏ
гьоᴴс<genII><sub><essive><lative>:сидлалӏил
гьоᴴс<super><essive>:сидкьа
гьоᴴс<super><essive><genII>:сидкьала
гьоᴴс<super><essive><genII><ablative>:сидкьалас
гьоᴴс<super><essive><genII><lative>:сидкьалал
гьоᴴс<super><essive><genII><translative>:сидкьалакьа̄
гьоᴴс<super><essive><ablative>:сидкьас
гьоᴴс<super><essive><dir>:сидкьада̄
гьоᴴс<super><essive><dir><ablative>:сидкьада̄с
гьоᴴс<super><essive><dir><lative>:сидкьада̄л
гьоᴴс<super><essive><dir><translative>:сидкьада̄кьа̄
гьоᴴс<super><essive><lative>:сидкьал
гьоᴴс<super><essive><translative>:сидкьалкьа̄
гьоᴴс<ad><essive>:сидгъа
гьоᴴс<ad><essive><genII><ablative>:сидгъалас
гьоᴴс<ad><essive><genII><lative>:сидгъалал
гьоᴴс<ad><essive><genII><translative>:сидгъалакьа̄
гьоᴴс<ad><essive><ablative>:сидгъас
гьоᴴс<ad><essive><dir>:сидгъада̄
гьоᴴс<ad><essive><dir><ablative>:сидгъада̄с
гьоᴴс<ad><essive><dir><lative>:сидгъада̄л
гьоᴴс<ad><essive><dir><translative>:сидгъада̄кьа̄
гьоᴴс<ad><essive><lative>:сидгъал
гьоᴴс<ad><essive><translative>:сидгъалкьа̄
гьоᴴс<apud><essive>:сиддой
гьоᴴс<apud><essive><ablative>:сиддойс
гьоᴴс<apud><essive><dir>:сиддойда̄
гьоᴴс<apud><essive><dir><ablative>:сиддойда̄с
гьоᴴс<apud><essive><dir><lative>:сиддойда̄л
гьоᴴс<apud><essive><dir><translative>:сиддойда̄кьа̄
гьоᴴс<apud><essive><lative>:сиддойл
гьоᴴс<apud><essive><translative>:сиддойкьа̄
гьоᴴс<cum><essive>:сидгъой
гьоᴴс<cum><essive><ablative>:сидгъойс
гьоᴴс<cum><essive><dir>:сидгъойда̄
гьоᴴс<cum><essive><dir><ablative>:сидгъойда̄с
гьоᴴс<cum><essive><dir><lative>:сидгъойда̄л
гьоᴴс<cum><essive><dir><translative>:сидгъойда̄кьа̄
гьоᴴс<cum><essive><lative>:сидгъойл
гьоᴴс<cum><essive><translative>:сидгъойкьа̄
гьоᴴс<poss><essive>:сидхъа
гьоᴴс<poss><essive><ablative>:сидхъас
гьоᴴс<poss><essive><dir>:сидхъада̄
гьоᴴс<poss><essive><dir><ablative>:сидхъада̄с
гьоᴴс<poss><essive><dir><lative>:сидхъада̄л
гьоᴴс<poss><essive><dir><translative>:сидхъада̄кьа̄
гьоᴴс<poss><essive><lative>:сидхъал
гьоᴴс<poss><essive><translative>:сидхъалкьа̄
сийо<obl><super><essive><indf>:лъинкьади
сийо<obl><super><essive><neg>:лъинкьана
сийо<obl><ad><essive><indf>:лъингъади
сийо<obl><ad><essive><neg>:лъингъана
сийо<obl><apud><essive><indf>:лъиндойди
сийо<obl><apud><essive><neg>:лъиндойна
сийо<obl><cum><essive><indf>:лъингъойди
сийо<obl><cum><essive><neg>:лъингъойна
сийо<obl><poss><essive><indf>:лъинхъади
сийо<obl><poss><essive><neg>:лъинхъана
сийо<obl><dat>:лъинил
сийо<obl><dat><indf>:лъинилди
сийо<obl><dat><neg>:лъинилна
сийо<obl><erg>:лъини
сийо<obl><erg><indf>:лъиниди
сийо<obl><erg><neg>:лъинина
сийо<obl><genI>:лъинис
сийо<obl><genI><indf>:лъинисди
сийо<obl><genI><neg>:лъинисна
сийо<obl><genII>:лъинила
сийо<obl><genII><indf>:лъинилади
сийо<obl><genII><neg>:лъинилана
сийо<obl><ins>:лъинид
сийо<obl><ins><indf>:лъинидди
сийо<obl><ins><neg>:лъинидна
сийо<obl><sub><essive><indf>:лъинилӏди
сийо<obl><sub><essive><neg>:лъинилӏна
сийо<obl><cont><essive><indf>:лъинилъди
сийо<obl><cont><essive><neg>:лъинилъна
сийо<obl><in><essive><indf>:лъиниъди
сийо<obl><in><essive><neg>:лъиниъна
сукӏо<obl><erg>:лъо
сукӏо<obl><erg><indf>:лъоди
сукӏо<obl><erg><neg>:лъона
сукӏо<obl><genI>:лъой
сукӏо<obl><genI><indf>:лъойсди
сукӏо<obl><genI><neg>:лъойна
сукӏо<obl><dat>:лъо̄л
сукӏо<obl><dat><indf>:лъо̄лди
сукӏо<obl><dat><neg>:лъо̄лна
сукӏо<obl><genII>:лъо̄ла
сукӏо<obl><genII><indf>:лъо̄лади
сукӏо<obl><genII><neg>:лъо̄лана
сукӏо<obl><ins>:лъо̄д
сукӏо<obl><ins><indf>:лъо̄дди
сукӏо<obl><ins><neg>:лъо̄дна
сукӏо<obl><super><essive><indf>:лъо̄кьади
сукӏо<obl><super><essive><neg>:лъо̄кьана
сукӏо<obl><ad><essive><indf>:лъо̄гъади
сукӏо<obl><ad><essive><neg>:лъо̄гъана
сукӏо<obl><apud><essive><indf>:лъо̄дойди
сукӏо<obl><apud><essive><neg>:лъо̄дойна
сукӏо<obl><cum><essive><indf>:лъо̄гъойди
сукӏо<obl><cum><essive><neg>:лъо̄гъойна
сукӏо<obl><sub><essive><indf>:лъо̄лӏди
сукӏо<obl><sub><essive><neg>:лъо̄лӏна
сукӏо<obl><cont><essive><ablative>:лъо̄лъсо
сукӏо<obl><cont><essive><lative>:лъо̄лъил
сукӏо<obl><cont><essive><indf>:лъо̄лъди
сукӏо<obl><cont><essive><neg>:лъо̄лъна
сукӏо<obl><in><essive><ablative>:лъо̄ъос
сукӏо<obl><in><essive><lative>:лъо̄ъол
сукӏо<obl><in><essive><indf>:лъо̄ъди
сукӏо<obl><in><essive><neg>:лъо̄ъна
сукӏо<obl><poss><essive><indf>:лъо̄хъади
сукӏо<obl><poss><essive><neg>:лъо̄хъана
сийо<abs>:сийо
сийо<abs><indf>:сийоди
сийо<abs><neg>:сийона
сийо<abs><neg><univ>:сийоназу
сукӏо<abs>:сукӏо
сукӏо<abs><indf>:сукӏоди
сукӏо<abs><neg>:сукӏона
сукӏо<abs><neg><univ>:сукӏоназу
до<obl><dat>:дил
до<obl><genI>:дие
до<obl><genII>:диела
до<abs>:до
до<erg>:до
до<obl><genII><super><essive><ablative>:дӣлакьас
до<obl><ins>:дӣд
до<obl><super><essive>:дӣкьа
до<obl><super><essive><genII><ablative>:дӣкьалас
до<obl><super><essive><ablative>:дӣкьас
до<obl><super><essive><dir><translative>:дӣкьада̄кьа̄
до<obl><super><essive><lative>:дӣкьал
до<obl><super><essive><translative>:дӣкьалкьа̄
до<obl><sub><essive><ablative>:дӣлӏсо
жуь<refl><obl><super><essive>:гьинкьа
жуь<refl><obl><ad><essive>:гьингъа
жуь<refl><obl><apud><essive>:гьиндой
жуь<refl><obl><cum><essive>:гьингъой
жуь<refl><obl><poss><essive>:гьинхъа
жуь<refl><obl><dat>:гьинил
жуь<refl><obl><erg>:гьини
жуь<refl><obl><genI>:гьинис
жуь<refl><obl><genII>:гьинила
жуь<refl><obl><ins>:гьинид
жуь<refl><obl><sub><essive>:гьинилӏ
жуь<refl><obl><cont><essive>:гьинилъ
жуь<refl><obl><in><essive>:гьиниъ
жуь<refl><pl><obl><dat>:гьидел
жуь<refl><pl><obl><erg>:гьиде
жуь<refl><pl><obl><genI>:гьидеш
жуь<refl><pl><obl><genII>:гьидела
жуь<refl><pl><obl><ins>:гьидед
жуь<refl><pl><obl><super><essive>:гьидекьа
жуь<refl><pl><obl><ad><essive>:гьидегъа
жуь<refl><pl><obl><apud><essive>:гьидедой
жуь<refl><pl><obl><cum><essive>:гьидегъой
жуь<refl><pl><obl><sub><essive>:гьиделӏ
жуь<refl><pl><obl><cont><essive>:гьиделъ
жуь<refl><pl><obl><in><essive>:гьидеъ
жуь<refl><pl><obl><poss><essive>:гьидехъа
ми<obl><genII>:дибола
ми<obl><genI>:дибо
ми<obl><dat>:дул
ми<obl><ins>:дӯд
ми<abs>:ми
ми<erg>:ми
миже<obl><dat>:мизол
миже<obl><genI>:мизос
миже<obl><genII>:мизола
миже<obl><ins>:мизод
миже<abs>:миже
миже<erg>:миже
хъона<ord>:хъонас
хъона<mult><part>:хъовахна
